import {regions} from './regions.js?v=20260927-5';
import {scenes,regionById,axisNames,questionMap,blankSession,flowFor,selectedFor,recommend,itineraryFor,validateSession,compareProfiles,mirrorFor} from './journey.js?v=20260927-5';
import {renderResult,renderRegionGuide} from './result-view.js?v=20260927-5';
import {reportFor} from './report.js?v=20260927-5';
import {sceneDetail} from './visuals.js?v=20260927-5';
import {buildAiHandoff} from './handoff.js?v=20260927-5';
import {createTravelCard} from './souvenir.js?v=20260927-5';
import {sceneImage,originalImageUrl} from './media.js?v=20260927-5';
import {classicExplorer,classicDialogBody,classicById} from './classic-view.js?v=20260927-5';
import {corridors,corridorById} from './corridors.js?v=20260927-5';
import {corridorExplorer,corridorDialogBody,nearbySection,placeDialogBody,placeById} from './corridor-view.js?v=20260927-5';
import {initAnalytics,track,analyticsStatus,setAnalyticsEnabled,shareUrl} from './analytics.js?v=20260927-5';
const publicUrl='https://asimovvong.github.io/xinxiang-caiyun/';
let lastCard=null,cardGeneration=0;
const $=s=>document.querySelector(s);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='caiyun-web-journey-v2';
let state=blankSession(),routeChoice=null,saveFailed=false;
try{const saved=localStorage.getItem(key);if(saved)state=validateSession(JSON.parse(saved));}catch{saveFailed=true;}
const person=()=>state.profiles[state.active];
const img=(id,cls='',lazy=true)=>sceneImage(scenes[id]?.image||'yunnan-atlas',{className:cls,alt:scenes[id]?.sub?scenes[id].sub+'区域情境插画，非当地实景照片':'云南风物艺术图鉴，非实景照片',priority:!lazy,sizes:cls==='option-thumb'?'80px':'(max-width:650px) 92vw, (max-width:1000px) 50vw, 640px'});
function save(){try{localStorage.setItem(key,JSON.stringify(state));saveFailed=false;}catch{saveFailed=true;toast('此浏览器无法保存，请通过“保存与导出”下载手记。');}}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('visible'),3800);}
function modal(title,body,wide=false){$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=body;$('#dialog').classList.toggle('wide',wide);$('#dialog').classList.toggle('atlas-dialog',body.includes('class="atlas-tabs"'));if(!$('#dialog').open)$('#dialog').showModal();$('#dialog').scrollTop=0;$('#dialog-body').scrollTop=0;$('#dialog-title').focus({preventScroll:true});}
function navigate(view){$('#dialog').close();state.view=view;routeChoice=person().routeId||null;save();render(true);}
function activeResult(){return recommend(person(),state.settings);}
function render(top=false){
  if(!routeChoice&&person().routeId)routeChoice=person().routeId;
  $('#profile-name').textContent=person().name||'我';$('#avatar').textContent=(person().name||'我').slice(0,1);
  document.body.dataset.view=state.view;
  if(state.view==='journey'&&person().focus===null)state.view='home';
  const renders={home:home,journey:journey,results:results,compare:compare};
  $('#main').innerHTML=(renders[state.view]||home)();
  if(top){window.scrollTo({top:0,behavior:'instant'});$('#main').focus({preventScroll:true});}
}
function sceneCard(id,small=false){return `<button class="scene-card ${small?'small':''}" data-action="choose-scene" data-id="${id}">${sceneImage(scenes[id].image,{alt:scenes[id].sub+'区域情境插画，非实景照片',priority:id==='dali',sizes:small?'(max-width:650px) 85vw, 480px':'(max-width:420px) 630px, (max-width:800px) 770px, 900px'})}<span class="scene-card-copy"><small>${escape(scenes[id].sub)}</small><strong>${escape(scenes[id].title)}</strong><span class="scene-entry">走进这个下午 <span aria-hidden="true">↗</span></span></span></button>`;}
function entryButtons(){return `<div class="entry-grid" aria-label="直接打开云南探索入口"><button class="entry-door" data-action="atlas"><span class="entry-symbol" aria-hidden="true">山</span><span><strong>云南互动地图</strong><small>看方位、海拔与风物</small></span><span aria-hidden="true">↗</span></button><button class="entry-door" data-action="classic-directory"><span class="entry-symbol" aria-hidden="true">路</span><span><strong>经典目的地与线路</strong><small>大理、丽江、版纳怎么选</small></span><span aria-hidden="true">↗</span></button><button class="entry-door" data-action="region-directory"><span class="entry-symbol" aria-hidden="true">日</span><span><strong>各地具体的一天</strong><small>吃什么、怎么玩、接受什么</small></span><span aria-hidden="true">↗</span></button><button class="entry-door" data-action="results"><span class="entry-symbol" aria-hidden="true">心</span><span><strong>我的旅行结论</strong><small>${person().focus===null?'留下线索后，在这里看建议':'路线、节奏与每天的安排'}</small></span><span aria-hidden="true">↗</span></button></div><div class="entry-tools" aria-label="带走答案与同行"><button data-action="ai-handoff">复制给 AI <span>↗</span></button><button data-action="souvenir">旅行小卡 <span>↗</span></button><button data-action="compare">同行对照 <span>↗</span></button><button data-action="storage">保存与导入 <span>↗</span></button></div>`;}
function entryDialog(){modal('你想从哪里打开云南？',`<p class="entry-dialog-intro">每一个入口，都可以直接打开。探索到一半也能回来，你的答案会留下。</p><button class="primary hub-begin" data-action="begin">${person().focus===null?'开始探寻之旅':person().complete?'回看这次的向往':'继续我的探寻'} <span aria-hidden="true">↗</span></button>${entryButtons()}`);}
function regionDirectory(){return `<p class="directory-intro">先借一个具体的下午，认识一个地方。点开就能看到一天怎么过、当地味道，以及需要接受的代价。</p><div class="region-directory">${[{title:'苍山洱海 · 雪山藏地',ids:['dali','lijiang','shangrila','shaxi']},{title:'春城蓝湖 · 滇南烟火',ids:['kunming','fuxian','jianshui','mengzi','mile','yuanyang']},{title:'边城风味 · 温泉古镇',ids:['mangshi','tengchong']},{title:'热带植物 · 茶山村寨',ids:['xishuangbanna','puer','jingmai']}].map(group=>`<section><h3>${group.title}</h3><div class="region-directory-grid">${group.ids.map(id=>`<button data-action="region" data-id="${id}">${img(id)}<span><strong>${escape(regionById[id].name)}</strong><small>${escape(scenes[id].title)}</small><em>打开这一天 ↗</em></span></button>`).join('')}</div></section>`).join('')}</div>`;}
function atlasDialog(tab='map'){if(!['map','art','places'].includes(tab))tab='map';const tabs=[['map','互动地图'],['art','山水图鉴'],['places','各地的一天']];modal('云南山水风物图鉴',`<div class="atlas-tabs" aria-label="图鉴内容">${tabs.map(([id,label])=>`<button data-action="atlas-tab" data-id="${id}" aria-pressed="${id===tab}">${label}</button>`).join('')}</div>${tab==='map'?`<p class="atlas-caption">看清雪山、湖泊、古城与雨林在哪里。地图可缩放、点选。<a href="atlas.html?v=20260927-5-atlas" target="_blank" rel="noopener">单独打开完整地图与资料 ↗</a></p><iframe class="atlas-frame atlas-direct-map" src="atlas.html?v=20260927-5-atlas&compact=1" title="云南16州市可缩放互动风物地图"></iframe><div class="atlas-map-actions"><button class="secondary" data-action="region-directory">打开各地的一天 ↗</button><button class="text-link" data-action="atlas-tab" data-id="art">看看山水插画图鉴</button></div>`:tab==='art'?`<p class="atlas-caption">从雪山峡谷，到湖泊、梯田与雨林。全年艺术示意，不代表同一季节能看到所有景观。</p><div class="atlas-art-preview">${sceneImage('yunnan-atlas',{alt:'云南山水风物艺术图鉴',sizes:'(max-width:650px) 90vw, 840px'})}<button class="secondary" data-action="atlas-original">放大看高清原图 ↗</button></div>`:regionDirectory()}`,true);}
function home(){const p=person(),count=selectedFor(p).filter(x=>x.option).length;return `
<section class="opening entry-opening">
 <div class="opening-copy"><div class="chapter-line"><span>一场关于向往的旅行</span><span>心向彩云</span></div><h1>去云南，<br>你想过哪一种日子？</h1><p class="lead">攻略存满了，还是选不出？<br>从具体的一天，找到真正想去的云南。</p><div class="entry-start"><button class="primary begin-explore" data-action="begin">${p.focus===null?'开始探寻之旅':p.complete?'回看这次的向往':'继续我的探寻'} <span aria-hidden="true">↗</span></button><small>${count?`已留下 ${count} 个线索 · 已自动保存`:'不用登录 · 可以说不确定 · 答案留在本机'}</small></div>${entryButtons()}</div>
 <div class="first-scenes">${sceneCard('dali')}${sceneCard('shangrila')}${sceneCard('mangshi')}</div>
</section>
<section class="how-it-works"><p>从“哪里都想去”，走到“这次就这样过”。</p><ol><li><b>看见心动</b><span>进入具体的一天</span></li><li><b>分清期待</b><span>用追问和取舍确认</span></li><li><b>安排云南</b><span>喜欢的地方，合适的节奏</span></li><li><b>带走答案</b><span>AI 接力／旅行小卡</span></li></ol></section>${classicExplorer()}<section class="more-scenes"><div class="section-line"><h2>还没选定方向？借一个下午，试试直觉</h2><span>不必全选，先跟着直觉走</span></div><div class="scene-strip">${['jianshui','kunming','fuxian','lijiang'].map(id=>sceneCard(id,true)).join('')}</div><p class="art-caption">场景为原创情境插画，非真实照片；晴空、花木与水色不代表国庆实景。</p></section>
 <section class="atlas-invite">${sceneImage('yunnan-atlas',{alt:'云南山水风物艺术图鉴',sizes:'(max-width:800px) 90vw, 640px'})}<div><h2>如果还不知道<br>云南有多少种样子。</h2><p>从雪山峡谷，到高原湖泊、梯田与雨林。把地理、吃食与地方生活先放到眼前。</p><button class="secondary" data-action="atlas">展开云南风物图鉴</button></div></section><section class="inspiration-section"><div class="section-line"><h2>云南，还可以把你好奇的事放大</h2><span>延伸灵感 · 不自动加入这次路线</span></div><div class="inspiration-grid"><button data-action="inspiration" data-id="tea"><span>普洱 · 景迈山</span><h3>一杯茶，<br>从哪一种生活里长出来？</h3><p>茶林、森林与村寨的关系。</p></button><button data-action="inspiration" data-id="terrace"><span>红河 · 元阳</span><h3>如果没有水镜，<br>你还想看什么？</h3><p>田埂、山势，和仍在发生的农事。</p></button><button data-action="inspiration" data-id="gorge"><span>滇西北 · 怒江</span><h3>如果一路在移动，<br>沿途能不能就是目的？</h3><p>峡谷、江水与村寨不断变换的关系。</p></button></div></section>`;}
function journey(){
  const p=person(),flow=flowFor(p);p.cursor=Math.min(p.cursor,flow.length-1);
  const q=flow[p.cursor],picked=p.answers[q.id],option=q.options.find(o=>o.id===picked),sceneId=q.id==='mirror'?(scenes[p.focus]?p.focus:'dali'):q.scene;
  const s=scenes[sceneId],known=selectedFor(p).filter(x=>x.option&&x.option.id!=='unknown').length;
  const progress=Math.round((p.cursor+1)/flow.length*100);
  let options=q.id==='contrast'?q.options.filter(o=>o.id!==p.focus):q.options;
  if(q.id==='anchor')options=q.options.filter(o=>!(o.id==='primary'&&!regionById[p.focus])&&!(o.id==='contrast'&&(!regionById[p.answers.contrast]||p.answers.contrast===p.focus))).map(o=>{const id=o.id==='primary'?p.focus:o.id==='contrast'?p.answers.contrast:null;const pull=questionMap[id+'_pull'];const chosen=pull?.options.find(x=>x.id===p.answers[pull.id]);return id?{...o,label:chosen&&chosen.id!=='unknown'?chosen.label:scenes[id].title,detail:regionById[id].name+'里的这份期待；如果没有，会更遗憾。'}:o;});
  return `<div class="journey-top"><button class="text-link" data-action="back">${p.cursor?'上一段':'重新看场景'}</button><div class="chapter-progress"><span>${escape(q.stage)}</span><div><i style="width:${progress}%"></i></div><span>已留下 ${known} 个线索</span></div><button class="text-link" data-action="results">先看愿望草图</button></div>
  <section class="journey-layout">
  <aside class="scene-stage"><div class="scene-visual">${img(sceneId,'scene-image',false)}<button class="image-detail" data-action="region" data-id="${sceneId}">认识${regionById[sceneId].name}</button><div class="scene-overlay"><span>${escape(s.sub)}</span><h2>${escape(s.title)}</h2></div></div><div class="sensory"><p>${escape(s.sensory)}</p><div class="scene-facts"><span>${escape(regionById[sceneId].food)}</span><button data-action="region" data-id="${sceneId}">这一天的细节</button></div><small>情境插画，非实景或当季景观承诺</small></div><div class="scene-explainer">${sceneDetail(sceneId,'compact')}</div></aside>
  <article class="conversation"><div class="question-heading"><span class="question-number">${String(p.cursor+1).padStart(2,'0')}</span><span>把向往说具体</span></div><h1>${escape(q.title)}</h1><p class="question-context">${escape(q.context)}</p>
  ${q.id==='mirror'?`<blockquote class="mirror-draft">${escape(mirrorFor(p).text)}</blockquote>`:''}
  ${q.id==='transfer'?timeRibbon():''}
  <div class="options ${q.id==='contrast'?'contrast-options':''}" role="group" aria-label="${escape(q.title)}">${options.map((o,i)=>`<button class="option ${picked===o.id?'chosen':''} ${o.id==='unknown'?'unknown-option':''}" data-action="answer" data-question="${q.id}" data-id="${o.id}" aria-pressed="${picked===o.id}">${q.id==='contrast'&&scenes[o.id]?img(o.id,'option-thumb'):''}<span class="option-index">${picked===o.id?'✓':o.id==='unknown'?'…':String.fromCharCode(65+i)}</span><span><strong>${escape(o.label)}</strong><small>${escape(o.detail)}</small></span></button>`).join('')}</div>
  ${option?`<div class="response" aria-live="polite"><span class="response-mark">云</span><p>${escape(option.echo||'这个答案已记下。我们继续让它更具体一点。')}</p></div>`:''}
  <details class="your-words" ${p.notes[q.id]?'open':''}><summary>也想用自己的话补一句</summary><label for="note">你的原话会保留在手记里，不自动归类或打分。</label><textarea id="note" data-note="${q.id}" maxlength="500" rows="3" placeholder="也许还有一种选项，没有写出我的感觉……">${escape(p.notes[q.id]||'')}</textarea></details>
  <div class="conversation-foot"><small>${saveFailed?'请导出备份，以免丢失':'已自动保存在此浏览器'}</small><button class="primary" data-action="next" ${!picked?'disabled':''}>${p.cursor===flow.length-1?'整理这次的向往':'沿着这个想法，再往下看看'} <span aria-hidden="true">↗</span></button></div>
  </article></section>`;
}
function timeRibbon(){const n=state.settings.days;return `<div class="time-ribbon"><div><strong>${n} 天，不是 ${n} 个完整游玩日</strong><button data-action="settings">调整天数</button></div><div class="day-boxes">${Array.from({length:n},(_,i)=>`<span class="${i===0||i===n-1?'travel':'stay'}">${i===0?'到达':i===n-1?'返程':'停留'}</span>`).join('')}</div><small>每增加一次跨地区换住，再拿走一个“停留”格。</small></div>`;}
function evidencePanel(result){const p=person(),mirror=mirrorFor(p),mainAxis=result.axes[0];return `<section class="wish-note"><div class="section-line"><h2>关于这次的你，我先这样记下</h2><button class="text-link" data-action="edit-question" data-id="mirror">确认或纠正</button></div>
<div class="wish-grid"><div class="wish-main"><span class="tag">${mirror.confirmed?'你已确认的理解':p.answers.mirror==='change'?'你希望重新澄清':'等待你确认的理解'}</span><p>${escape(p.answers.mirror==='change'?'你没有完全认同之前的复述。下面保留原答案，建议还需要按你的意思修正。':mirror.text)}</p>${p.answers.mirror==='change'&&p.answers.clarify&&p.answers.clarify!=='unknown'?`<p>你后来明确想保住的是：<strong>${escape(questionMap.clarify.options.find(o=>o.id===p.answers.clarify).label)}</strong>。</p>`:''}${result.protectedRegion?`<div class="protected-wish"><strong>你最不想删掉：${regionById[result.protectedRegion].name}里的那份体验</strong><p>${result.ranked.find(d=>d.id===result.protectedRegion).excluded?'但它和你当前的排除或高原边界冲突。先保留这份向往，不强行编排行程。':'时间草案会优先保留它。较高的平均分不等于可以替你放弃。'}</p><button class="text-link" data-action="edit-question" data-id="anchor">重新看看这个取舍</button></div>`:''}</div><div class="wish-axes"><h3>目前更有分量的线索</h3>${result.axes.slice(0,4).map(([axis,w])=>`<div><span>${axisNames[axis]}</span><i><b style="width:${Math.round(w/mainAxis[1]*100)}%"></b></i></div>`).join('')}<small>表示所选线索的相对分量，不是人格比例。</small></div></div>
<div class="evidence-list">${result.selected.filter(x=>x.option&&x.option.id!=='unknown'&&x.option.echo).slice(0,4).map(({question,option})=>`<div><span>${escape(question.title)}</span><strong>“${escape(option.label)}”</strong><button data-action="edit-question" data-id="${question.id}">改一处</button></div>`).join('')}</div></section>`;}
function results(){const p=person(),r=activeResult();
 if(!r.hasPreferences)return `<section class="empty-state"><h1>还不用急着得出答案。</h1><p>目前的回答还不足以形成一个方向。留下“不确定”没有关系，可以从一个更小的画面继续。</p><button class="primary" data-action="resume">回到场景，继续想想</button><button class="secondary" data-action="atlas">先认识云南</button></section>`;
 if(!r.ranked.some(d=>!d.excluded))return `<section class="empty-state"><h1>这次先没有合适的候选。</h1><p>你已排除全部地区。可以恢复一个想再看看的地方。</p><div class="button-row">${r.ranked.map(d=>p.excluded.includes(d.id)?`<button class="secondary" data-action="exclude" data-id="${d.id}">恢复${d.name}</button>`:`<button class="secondary" data-action="edit-question" data-id="altitude">重新考虑高原意愿</button>`).join('')}</div></section>`;
 const route=r.available.find(t=>t.id===routeChoice)||r.primary;
 return renderResult({profile:p,result:r,route,settings:state.settings,evidenceHtml:evidencePanel(r)});
}
function compare(){const c=compareProfiles(state);return `<div class="compare-page"><div class="section-line"><div><span class="tag">一起去，也可以有不同向往</span><h1>先各自回答，再找共同的一天。</h1><p>保留两个人的愿望，不把“不愿意”平均掉。</p></div><button class="secondary" data-action="profiles">切换填写人</button></div><div class="people-grid">${state.profiles.map((p,i)=>`<article><span class="avatar large">${escape(p.name.slice(0,1)||'旅')}</span><h2>${escape(p.name)}</h2><p>${c.results[i].hasPreferences?escape(c.results[i].style):'还没有留下足够的线索'}</p><div>${c.results[i].ranked.filter(r=>!r.excluded).slice(0,3).map(r=>c.results[i].hasPreferences?`<span class="tag">${r.name} ${r.score}</span>`:'').join('')}</div><button class="primary" data-action="switch" data-id="${i}">${i===state.active?'继续我的探索':'切换并独立填写'}</button></article>`).join('')}</div>
${c.bothReady?`<section><h2>目前可以一起讨论的方向</h2><p>共同分优先照顾较不心动的一方；任何一方明确排除的地区，均不会成为共同推荐。它仍不是你们已作出的决定。</p><div class="shared-candidates">${c.common.filter(x=>!x.excluded).slice(0,3).map(x=>`<button data-action="region" data-id="${x.region.id}">${img(x.region.id)}<strong>${x.region.name}</strong><span>${escape(state.profiles[0].name)} ${x.values[0].score} / ${escape(state.profiles[1].name)} ${x.values[1].score}</span></button>`).join('')}</div></section><section class="differences"><h2>真正需要聊一聊的是这些</h2>${c.differences.length?c.differences.map(id=>`<article><h3>${escape(questionMap[id].title)}</h3>${state.profiles.map(p=>`<p><strong>${escape(p.name)}</strong>：${escape(questionMap[id].options.find(o=>o.id===p.answers[id]).label)}</p>`).join('')}<p class="gentle">先各说一个“如果这点没被满足，我会遗憾”的具体半天，再看能否安排到同一个基地。</p></article>`).join(''):'<p>已回答的关键选择暂未发现明显分歧；未回答的部分仍需各自确认。</p>'}</section>`:`<div class="empty-state"><h2>另一份真实答案，比猜测同伴更有用。</h2><p>可以在这台设备切换填写人；也可以请朋友在自己的设备答完后导出手记，再从“保存与导出”合并朋友的答案。</p></div>`}</div>`;}
function regionDialog(id){const r=regionById[id],s=scenes[id];modal(r.name+'，不止一个地名',`<div class="region-cover">${img(id,'',false)}<span>${escape(s.sub)}</span></div><p class="region-story">${escape(s.sensory)}</p>${renderRegionGuide(id)}<div class="region-detail-grid"><section><h3>当地旅行的节奏</h3><p>${escape(r.subtitle)}</p></section><section><h3>把味道记具体</h3><p>${escape(r.food)}</p><h3>也要接受</h3><p>${escape(r.tradeoff)}</p><h3>十月，不替风景作保证</h3><p>${escape(r.season)}</p></section></div><div class="region-question"><p>${escape(s.hook)}</p><button class="primary" data-action="choose-scene" data-id="${id}">从这里开始探寻</button></div><details><summary>地理与资料依据</summary><p>${escape(r.region)} · ${r.altitude===null?'海拔因具体位置而异，出行前另核':'城区或区域参考海拔约 '+r.altitude+' 米，景区具体位置不同'}。</p>${r.sources.map(x=>`<p><a href="${escape(x.url)}" target="_blank" rel="noopener noreferrer">${escape(x.title)}</a></p>`).join('')}<p>插画是场景想象，不是地理比例图或实景照片。</p></details>`,true);}
function settingsDialog(){const s=state.settings;modal('给这次旅行留多大空间',`<form id="settings-form"><label>总日历天数（含去回）<select name="days">${[3,4,5,6,7,8,9].map(n=>`<option ${s.days===n?'selected':''} value="${n}">${n} 天</option>`).join('')}</select></label><label>往返交通总预留<select name="travelDays"><option value="2" ${s.travelDays===2?'selected':''}>2 天，去回各一天</option><option value="1" ${s.travelDays===1?'selected':''}>1 天，只有已核实两端各半天才选</option></select></label><label>最多几个住宿基地<select name="maxBases">${[1,2,3].map(n=>`<option value="${n}" ${s.maxBases===n?'selected':''}>${n} 个基地，${n-1} 次换住</option>`).join('')}</select></label><label>每人预算目标（元，可留空）<input name="budget" type="number" min="0" max="1000000" step="1" value="${s.budget??''}" placeholder="暂时没定"></label><p>预算只记录目标，没有实时查询价格。转场会另外占用日程；选择“往返合计一天”也不增加完整停留日，只可能保留到达/返程的半天。</p><button class="primary" type="submit">按这些条件重新看安排</button></form>`);}
function journalAnswerLabel(p,q,o){
 if(q.id!=='anchor'||!['primary','contrast'].includes(o.id))return o.label;
 const id=o.id==='primary'?p.focus:p.answers.contrast,pull=questionMap[id+'_pull'],picked=pull?.options.find(x=>x.id===p.answers[pull.id]);
 return regionById[id]?regionById[id].name+'：'+(picked&&picked.id!=='unknown'?picked.label:scenes[id].title):o.label;
}
function journalText(){const p=person(),r=activeResult(),route=r.available.find(t=>t.id===routeChoice)||r.primary;return `心向彩云 · ${p.name}的云南愿望手记\n${new Date().toLocaleDateString('zh-CN')}\n\n这次更像：${r.style}\n理解状态：${p.answers.mirror==='yes'?'本人已确认':p.answers.mirror==='change'?'本人希望修正':'待本人确认'}\n${p.answers.mirror==='change'?'之前的复述已撤回，以我后来确认的答案和原话为准。':mirrorFor(p).text}\n\n${r.selected.filter(x=>x.option).map(({question,option})=>`${question.title}\n${journalAnswerLabel(p,question,option)}${p.notes[question.id]?'\n我的原话：'+p.notes[question.id]:''}`).join('\n\n')}\n\n旅行条件：${state.settings.days}个日历日；往返预留${state.settings.travelDays}天；最多${state.settings.maxBases}个住宿基地。\n预算目标：${state.settings.budget===null?'未定':state.settings.budget+'元/人，未核报价'}\n\n${r.hasPreferences?'候选：'+r.ranked.filter(x=>!x.excluded).slice(0,3).map(x=>x.name+' '+x.score+'分').join('；'):'还没有足够线索形成方向'}\n${route?'时间草案：'+route.name+'\n'+itineraryFor(route,r,state.settings).map(d=>'D'+d.day+' '+d.title+'：'+d.detail).join('\n'):''}\n\n待确认：${r.unknowns.map(q=>q.title).join('；')||'交通、天气、开放与实际报价'}\n这是偏好规则生成的探索草案，不是人格测评或已经预订的行程。自由文字原样保留，未被自动理解或打分。`;}
function journalDialog(){modal('把这一刻的想法带走',`<p>可以复制给同行的人继续聊，也可以下载留存。自由补充会以你的原话出现。</p><textarea class="journal-text" readonly aria-label="旅行手记全文">${escape(journalText())}</textarea><div class="button-row"><button class="primary" data-action="ai-handoff">复制给 AI（含提示词）</button><button class="secondary" data-action="souvenir">保存旅行小卡</button><button class="secondary" data-action="copy-journal">复制手记</button><button class="secondary" data-action="download-journal">下载文字版</button><button class="secondary" data-action="export">导出可恢复的答案</button></div>`);}
function aiDialog(both=false){
 const text=buildAiHandoff(state,{both,routeId:routeChoice});
 modal('复制给 AI，让这份探索继续',`<p>可以直接粘贴给 GPT、DeepSeek、豆包等。已包含测试目的、当前有效回答、本人原话、规则草案、未知条件，以及如何继续追问和规划的提示词。</p><div class="ai-scope"><button class="${both?'secondary':'primary'}" data-action="ai-handoff">只带我的答案</button><button class="${both?'primary':'secondary'}" data-action="ai-both">带上两个人的答案</button></div><p class="export-privacy">请先检查下面的文字；点击复制不会自动发送给任何 AI。自由补充和填写人称呼会包含在其中。</p><textarea class="journal-text ai-prompt" id="ai-prompt" aria-label="复制给AI的完整提示词" readonly>${escape(text)}</textarea><div class="button-row"><button class="primary" data-action="copy-ai">复制完整提示词与答案</button><button class="secondary" data-action="download-ai">下载 AI 版文字</button></div>`);
}
async function souvenirDialog(){
 const p=person(),r=activeResult(),route=r.available.find(t=>t.id===routeChoice)||r.primary;
 if(!r.hasPreferences||!route){modal('先留下一点向往，再做小卡',`<p>目前还没有合适的路线草案。继续探索或调整天数后，就能生成属于这次旅行的小卡。</p><button class="primary" data-action="close-resume">继续探索</button>`);return;}
 const generation=++cardGeneration,v=reportFor(p,r,route,state.settings),days=itineraryFor(route,r,state.settings);
 modal('正在制作你的云南小卡',`<p>把场景、旅行风格和这几天的安排放在一起……</p><div class="card-loading" aria-label="正在生成"></div>`);
 try{
  const card=await createTravelCard({title:v.style,subtitle:v.action,routeName:v.title,regionIds:v.ids,days:v.days,nights:v.nights,keywords:v.keywords,dayLabels:days,publicUrl:shareUrl('card'),provisional:v.provisional});
  if(generation!==cardGeneration||!$('#dialog').open||$('#dialog-title').textContent!=='正在制作你的云南小卡')return;
  lastCard=card;track('card_generated');
  modal('我的云南旅行小卡',`<p>保存后可以发朋友圈或小红书。小卡只展示旅行风格、路线与日程，不包含姓名和自由补充。二维码指向公开探索网页。</p><img class="souvenir-preview" src="${card.dataUrl}" alt="${escape(v.title+' · '+v.style+' · '+v.days+'天云南旅行愿望小卡')}"><div class="button-row"><a class="primary" href="${card.dataUrl}" download="心向彩云-我的云南旅行小卡.png" data-action="card-download">保存高清 PNG</a>${typeof navigator.share==='function'?'<button class="secondary" data-action="share-card">分享小卡</button>':''}<button class="secondary" data-action="copy-site">复制网页链接</button></div><p class="save-image-hint">手机可长按图片保存；电脑可右键“图片另存为”。如果内置浏览器没有响应下载，请使用这两种方式。</p>`,true);
 }catch{modal('小卡暂时没有生成',`<p>场景图片尚未读取成功，请检查网络后重试。答案仍保存在此浏览器。</p><button class="primary" data-action="souvenir">重新生成</button>`);}
}
function download(name,text,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function storageDialog(){modal('保存、导出与两人汇总',`<p>选择会自动保存在当前浏览器。更换设备、无痕浏览或清理浏览数据可能使它丢失；下载一份 JSON 就能恢复。</p><div class="storage-actions"><button class="primary" data-action="ai-handoff">复制给 AI，继续分析与规划</button><button class="secondary" data-action="souvenir">生成并保存云南旅行小卡</button><button class="secondary" data-action="export">下载完整答案备份</button><button class="secondary" data-action="import">导入备份或朋友的答案</button><button class="secondary" data-action="paste-import">粘贴备份文字来恢复</button><button class="secondary" data-action="journal">复制／下载我的文字手记</button></div><button class="text-link danger" data-action="reset-prompt">重新开始当前填写人的探索</button>`);}
function profilesDialog(){modal('谁在回答这一轮',`<p>先各自回答，再一起对照。姓名只是本机的区分标签，可以用昵称。</p><form id="profiles-form">${state.profiles.map((p,i)=>`<label>填写人 ${i+1}<input name="name${i}" maxlength="20" value="${escape(p.name)}" required></label>`).join('')}<button class="secondary" type="submit">保存称呼</button></form><div class="button-row">${state.profiles.map((p,i)=>`<button class="${i===state.active?'primary':'secondary'}" data-action="switch" data-id="${i}">${escape(p.name)}${i===state.active?' · 正在填写':''}</button>`).join('')}</div>`);}
function sourcesDialog(){modal('云南很具体，想象也需要边界',`<p>当前从经典目的地与线路出发，探索当地及附近的具体体验。资料核对于 2026 年 9 月；历史介绍用于认识地方特色，不代表国庆期间开放、票价与景观保证。</p>${regions.map(r=>`<section class="source-region"><h3>${r.name}</h3><p>${escape(r.season)}</p>${r.sources.map(s=>`<a href="${escape(s.url)}" target="_blank" rel="noopener noreferrer">${escape(s.title)}</a>`).join('')}</section>`).join('')}<p>原图鉴覆盖云南 16 个州市。图鉴元素是全年艺术示意，不能直接当成本次国庆可以同时看到的景观。所有场景插画均非真实照片。</p>`,true);}
function rulesDialog(){modal('建议如何从你的答案里长出来',`<ol class="rules-list"><li><strong>先记录，不急着定义。</strong>场景的第一眼吸引与后续具体选项一起保存。复述只有得到你的确认，才标成“已确认”。自由文字原样保留，不自动打分。</li><li><strong>匹配的是这次的愿望。</strong>山川、湖岸、文化、吃食、休息、陌生感、手作、植物、街头生活各有选项权重。地区特征用 1—5 的编辑评分，按你选择的权重算平均，再换算为 100 分；首选场景加 4 分。</li><li><strong>代价不会被平均掉。</strong>避开高原或明确不去优先于分数；不想依赖天气时，丽江和香格里拉减 5 分。明确改选稳定方向再减 8 分。未知高原意愿只给有条件候选。</li><li><strong>城市越多不自动得分越高。</strong>你明确最不想删掉的地区体验优先保留，但不越过排除与高原边界。其余组合取目的地均分，每次转场再扣 4 分（慢住扣 6 分）。每次转场保守预留一个日程格；慢住每基地至少两个完整活动日。夜数始终等于日历天数减一。</li><li><strong>两个人，先尊重底线。</strong>任一方排除的地区不参与共同建议；共同分为较低个人分的 70% 加个人均分的 30%。它用来开启讨论，不表示已经达成共识。</li><li><strong>没有“心理准确率”。</strong>这些是可解释的编辑规则，不是临床心理量表、读心结果或满意度预测。交通、价格与预约需要另查。</li></ol>`);}
function editQuestion(id){const p=person();if(p.focus===null)p.focus='unknown';if(id==='altitude'&&!flowFor(p).some(q=>q.id==='altitude')){modal('高原意愿',`<p>此项会影响香格里拉候选，也会影响丽江高处项目。</p>${questionMap.altitude.options.map(o=>`<button class="option" data-action="direct-altitude" data-id="${o.id}"><span><strong>${escape(o.label)}</strong><small>${escape(o.detail)}</small></span></button>`).join('')}`);return;}p.cursor=Math.max(0,flowFor(p).findIndex(q=>q.id===id));$('#dialog').close();navigate('journey');}
document.addEventListener('click',async e=>{
 const el=e.target.closest('[data-action]');if(!el)return;const {action,id,question}=el.dataset;const p=person();
 if(action==='begin'){if(p.focus!==null){navigate(p.complete?'results':'journey');return;}p.focus='unknown';p.cursor=0;track('explore_start');navigate('journey');return;}
 if(action==='entry-hub'){entryDialog();return;}
 if(action==='scroll-corridors'||action==='classic-directory'){modal('经典目的地与线路',classicExplorer(),true);return;}
 if(action==='region-directory'){modal('在云南，过具体的一天',regionDirectory(),true);return;}
 if(action==='atlas-tab'){atlasDialog(id);return;}
 if(action==='classic'){const c=classicById[id];if(c)modal(c.label,classicDialogBody(id),true);return;}
 if(action==='classic-start'){if(!regionById[id]||!classicById[el.dataset.route])return;p.entryRouteId=el.dataset.route;p.corridor=null;p.routeId=null;routeChoice=null;if(p.focus!==id){delete p.answers.mirror;delete p.answers.clarify;}p.focus=id;p.cursor=0;p.complete=false;track('explore_start');$('#dialog').close();navigate('journey');return;}
 if(action==='corridor'){const c=corridorById[id];if(c)modal(c.name,corridorDialogBody(id),true);return;}
 if(action==='corridor-start'){if(!regionById[id])return;p.corridor=el.dataset.corridor;p.routeId=null;routeChoice=null;if(p.focus!==id){delete p.answers.mirror;delete p.answers.clarify;}p.focus=id;p.cursor=0;p.complete=false;track('explore_start');$('#dialog').close();navigate('journey');return;}
 if(action==='place'){const r=activeResult(),route=r.available.find(t=>t.id===routeChoice)||r.primary,place=placeById[id];if(place)modal(place.name+'：把这一天说具体',placeDialogBody(id,{route,result:r,profile:p}),true);return;}
 if(action==='excursion'){
  const place=placeById[id];if(!place||place.kind==='overnight')return;
  p.excursions||={};const old=p.excursions[place.anchorBase];
  if(old===id)delete p.excursions[place.anchorBase];else p.excursions[place.anchorBase]=id;
  const r=activeResult(),route=r.available.find(t=>t.id===routeChoice)||r.primary;
  if(old!==id&&!itineraryFor(route,r,state.settings).some(d=>d.excursionId===id)){
   if(old)p.excursions[place.anchorBase]=old;else delete p.excursions[place.anchorBase];
   const status=route?.excursionStatus?.find(x=>x.placeId===id);modal('先给这一天留出位置',`<p>${escape(status?.reason||'当前路线没有适合替换的完整日，或这项体验与已明确的边界冲突。')}</p><p>你最舍不得的那一天会优先保留。可以增加天数、换一个基地，或先保持现在的安排。</p><div class="button-row"><button class="primary" data-action="settings">看看时间条件</button><button class="secondary" data-action="close">保留现在的安排</button></div>`);return;
  }
  save();$('#dialog').close();render();$('#travel-plan')?.scrollIntoView({block:'start'});toast(old===id?'已恢复原来的这一天。':'已替换一个完整日，假期没有被悄悄加长。');return;
 }
 if(action==='branch-route'){
  const place=placeById[id];if(!place)return;const destination=place.stayBaseId||place.id,r=activeResult();
  if(!r.hasPreferences){modal('先找到想怎样过的日子',`<p>${escape(place.tradeoff)}</p><button class="primary" data-action="corridor-start" data-id="${destination}" data-corridor="${place.corridorId}">从${escape(place.name)}开始探索</button>`);return;}
  const corridor=corridorById[place.corridorId],allowed=new Set(corridor.stayBases.map(b=>b.id));
  const options=r.routes.filter(t=>t.ids.includes(destination)&&t.ids.every(x=>allowed.has(x))).sort((a,b)=>a.blocked.length-b.blocked.length||a.moves-b.moves);
  modal('多住一个地方，时间会怎样变',`<p>${escape(place.tradeoff)}</p><div class="branch-route-list">${options.map(t=>`<article><h3>${escape(t.name)}</h3><p>${state.settings.days} 天 · ${t.fullDays} 个完整活动日 · ${t.moves} 次换住</p>${t.blocked.length?`<p class="route-unavailable">${t.blocked.map(escape).join('；')}</p>`:`<button class="primary" data-action="use-regional-route" data-id="${t.id}" data-corridor="${place.corridorId}">按这条线看看安排</button>`}</article>`).join('')}</div><button class="text-link" data-action="settings">调整天数或换住上限</button>`,true);return;
 }
 if(action==='use-regional-route'){if(!activeResult().available.some(r=>r.id===id))return;p.corridor=el.dataset.corridor;p.routeId=id;routeChoice=id;save();$('#dialog').close();state.view='results';save();render(true);return;}
 if(action==='card-download'){track('card_download_click');return;}
 if(action==='privacy'){const a=analyticsStatus();modal('答案留在这里，统计只看使用情况',`<p>你的称呼、问答、预算和自由补充只存在当前浏览器，导出或复制由你主动决定。</p><p>网站使用 GoatCounter 统计页面访问与固定功能事件，例如完成探索、成功复制给 AI、生成小卡。统计服务会处理请求中的网络信息，用于去重；不上传答案正文。</p><p>按钮点击只能表示操作，不等于朋友已经收到分享。浏览器拦截、网络与关闭统计都可能导致漏计。</p><p>统计状态：${a.enabled?'已允许':'当前未启用或已关闭'}。</p><button class="secondary" data-action="toggle-analytics">${a.enabled?'关闭本浏览器的使用统计':'允许本浏览器的使用统计'}</button><p><a href="https://www.goatcounter.com/help/privacy" target="_blank" rel="noopener noreferrer">查看统计服务说明</a></p>`);return;}
 if(action==='toggle-analytics'){setAnalyticsEnabled(!analyticsStatus().enabled);$('#dialog').close();toast('已保存本浏览器的统计偏好。');return;}
 if(action==='close'){cardGeneration++;$('#dialog').close();return;}
 if(action==='home'){navigate('home');return;}
 if(action==='scroll-plan'){$('#travel-plan')?.scrollIntoView({behavior:'smooth',block:'start'});return;}
 if(action==='ai-handoff'){aiDialog(false);return;}
 if(action==='ai-both'){aiDialog(true);return;}
 if(action==='copy-ai'){try{await navigator.clipboard.writeText($('#ai-prompt').value);track('ai_copy_success');toast('已复制完整提示词与答案，直接粘贴给你常用的 AI。');}catch{$('#ai-prompt').select();toast('请手动复制已选中的内容。');}return;}
 if(action==='download-ai'){download('心向彩云-给AI的旅行探索.txt',$('#ai-prompt').value);toast('已向浏览器发起文字下载。');return;}
 if(action==='souvenir'){await souvenirDialog();return;}
 if(action==='close-resume'){if(p.focus===null){p.focus='unknown';p.cursor=0;track('explore_start');}navigate('journey');return;}
 if(action==='copy-site'){try{await navigator.clipboard.writeText(shareUrl('friend'));track('share_link_copy');toast('公开网页链接已复制。');}catch{toast('公开网址：'+publicUrl);}return;}
 if(action==='share-card'){if(!lastCard)return;track('share_click');const file=new File([lastCard.blob],'心向彩云-我的云南旅行小卡.png',{type:'image/png'});try{if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'心向彩云 · 我的云南旅行愿望'});track('share_native_success');}else toast('此浏览器暂不支持直接分享图片，可以长按保存后分享。');}catch(err){if(err.name!=='AbortError')toast('请先保存图片，再从相册分享。');}return;}
 if(action==='choose-scene'){p.entryRouteId=null;p.corridor=null;p.routeId=null;routeChoice=null;track('explore_start');if(p.focus!==id){delete p.answers.mirror;delete p.answers.clarify;}p.focus=id;p.cursor=0;p.complete=false;$('#dialog').close();navigate('journey');return;}
 if(action==='answer'){const f=flowFor(p);if(p.answers[question]!==id&&f.findIndex(q=>q.id===question)<f.findIndex(q=>q.id==='mirror')){delete p.answers.mirror;delete p.answers.clarify;}p.answers[question]=id;save();render();return;}
 if(action==='next'){const f=flowFor(p);if(!p.answers[f[p.cursor].id])return;if(p.cursor<f.length-1){p.cursor++;save();render(true);}else{p.complete=true;if(activeResult().hasPreferences)track('explore_complete');navigate('results');}return;}
 if(action==='back'){if(p.cursor){p.cursor--;save();render(true);}else navigate('home');return;}
 if(action==='resume'){if(p.focus===null){p.focus='unknown';p.cursor=0;track('explore_start');}navigate('journey');return;}
 if(action==='results'){navigate('results');return;}
 if(action==='compare'){navigate('compare');return;}
 if(action==='profiles'){profilesDialog();return;}
 if(action==='switch'){state.active=Number(id);$('#dialog').close();navigate(person().focus?'journey':'home');return;}
 if(action==='region'){regionDialog(id);return;}
 if(action==='settings'){settingsDialog();return;}
 if(action==='route'){if(!activeResult().available.some(t=>t.id===id))return;routeChoice=id;p.routeId=id;save();render();$('#main .plan-section')?.scrollIntoView({block:'start'});return;}
 if(action==='edit-question'){editQuestion(id);return;}
 if(action==='direct-altitude'){p.answers.altitude=id;save();$('#dialog').close();render();return;}
 if(action==='exclude'){const ix=p.excluded.indexOf(id);if(ix<0)p.excluded.push(id);else p.excluded.splice(ix,1);routeChoice=null;save();render();return;}
 if(action==='journal'){journalDialog();return;}
 if(action==='copy-journal'){try{await navigator.clipboard.writeText(journalText());toast('手记已复制。');}catch{const t=$('.journal-text');t?.select();toast('浏览器限制了复制，请复制已选中的手记文字。');}return;}
 if(action==='download-journal'){download('心向彩云-旅行手记.txt',journalText());toast('已开始下载文字手记。');return;}
 if(action==='storage'){storageDialog();return;}
 if(action==='export'){const text=JSON.stringify(state,null,2);download('心向彩云-答案备份.json',text,'application/json');modal('答案备份：下载或复制都可以',`<p>已向浏览器发起下载。如果内置浏览器没有出现文件，可复制下方备份文字保存；以后从“粘贴备份文字来恢复”导入。</p><textarea class="journal-text" id="backup-text" readonly aria-label="JSON答案备份">${escape(text)}</textarea><div class="button-row"><button class="primary" data-action="copy-backup">复制备份文字</button><button class="secondary" data-action="download-backup">再次下载 JSON</button></div>`);return;}
 if(action==='download-backup'){download('心向彩云-答案备份.json',JSON.stringify(state,null,2),'application/json');toast('已向浏览器发起下载；没有文件时，可复制备份文字。');return;}
 if(action==='copy-backup'){try{await navigator.clipboard.writeText(JSON.stringify(state,null,2));toast('备份文字已复制，可以私下发给同行人或保存在备忘录。');}catch{$('#backup-text')?.select();toast('请手动复制已选中的备份文字。');}return;}
 if(action==='paste-import'){modal('粘贴完整的答案备份',`<p>粘贴从本网页复制的 JSON 备份。确认格式后，你仍可选择合并朋友的答案或恢复两人的备份。</p><textarea class="journal-text" id="paste-backup" aria-label="粘贴JSON备份" placeholder="把完整备份文字粘贴到这里"></textarea><button class="primary" data-action="parse-backup">读取这份备份</button>`);return;}
 if(action==='parse-backup'){receiveImport($('#paste-backup').value);return;}
 if(action==='import'){$('#import-input').value='';$('#import-input').click();return;}
 if(action==='rules'){rulesDialog();return;}
 if(action==='sources'){sourcesDialog();return;}
 if(action==='inspiration'){if(id==='tea'){regionDialog('jingmai');return;}if(id==='terrace'){regionDialog('yuanyang');return;}const cards={tea:{name:'景迈山：把一杯茶放回它生长的地方',text:'茶树与高树共同生长，传统村寨与茶林相邻。你可以好奇的，不只是哪杯好喝，还有为什么在林下种茶、茶林和生活怎样相处。这里需要单独安排山区进出和接待，不能当作普洱市区顺路停一下。',ask:'如果没有采茶体验，也没有拍到云海，只是看茶林、喝茶、听懂一点村寨生活，你还愿意专程留时间吗？',source:'https://whc.unesco.org/en/list/1665',sourceName:'UNESCO 景迈山古茶林文化景观'},terrace:{name:'元阳：漂亮画面背后的土地与生活',text:'森林、水系、村寨和梯田共同构成持续运作的农业景观。你可以为图案与光线而来，也可以看看人们怎样在山地生活。元阳需要独立安排山区交通；它不是建水市内的一个景点。',ask:'如果田里是当时真实的农事状态，而不是照片里的水镜或金黄，你还想看什么：田埂山势、村寨生活，还是决定等特定季节再来？',source:'https://whc.unesco.org/en/list/1111',sourceName:'UNESCO 红河哈尼梯田文化景观'},gorge:{name:'怒江：沿途也可以是旅行的内容',text:'沿江向前，水声与两岸山势不断改变位置，公路连接村寨和观景点。较长的公路移动本身就是体验的一部分；是否适合，要先看你愿不愿意把时间交给路。',ask:'如果一天有较多时间坐车，换来的是不断变化的峡谷风景，你更想沿路前行，还是到一个喜欢的地方住下来？',source:'https://jtyst.yn.gov.cn/xyxw/202601/t20260105_3431033.html',sourceName:'云南省交通运输厅：怒江美丽公路'}};const d=cards[id];modal(d.name,`<span class="tag">延伸灵感 · 暂不参与核心匹配</span><p class="region-story">${escape(d.text)}</p><blockquote class="mirror-draft">${escape(d.ask)}</blockquote><p>先把这份好奇记住，再另核交通、季节与时间。本页不保证采茶、云海、梯田水镜或具体道路条件。</p><p><a href="${d.source}" target="_blank" rel="noopener noreferrer">${d.sourceName}</a></p><button class="secondary" data-action="atlas">看看它在云南哪里</button>`);return;}
 if(action==='atlas-original'){modal('云南山水风物图鉴 · 原图',`<p>双指或浏览器缩放可查看细节。原图按需加载，保留你喜欢的笔触与文字。</p><div class="atlas-original">${sceneImage('yunnan-atlas',{fullResolution:true,priority:true,alt:'云南山水风物艺术图鉴原图'})}</div><a class="text-link" href="${originalImageUrl('yunnan-atlas')}" target="_blank" rel="noopener">单独打开原图 ↗</a>`,true);return;}
 if(action==='atlas'){atlasDialog();return;}
 if(action==='reset-prompt'){modal('重新开始这位填写人的探索',`<p>只重置“${escape(p.name)}”的当前答案。可先下载备份，另一位的答案会保留。</p><div class="button-row"><button class="secondary" data-action="export">先下载备份</button><button class="primary" data-action="reset">确认重新开始</button></div>`);return;}
 if(action==='reset'){const name=p.name;state.profiles[state.active]=blankSession().profiles[0];person().name=name;$('#dialog').close();navigate('home');return;}
 if(action==='restore-backup'){state=windowPendingImport;routeChoice=person().routeId||null;windowPendingImport=null;$('#dialog').close();save();render(true);toast('已恢复这份备份。');return;}
 if(action==='merge-friend'){const incoming=windowPendingImport.profiles[windowPendingImport.active];state.profiles[1-state.active]=incoming;windowPendingImport=null;$('#dialog').close();save();navigate('compare');toast('已导入对方当前填写人的答案。');return;}
});
document.addEventListener('change',e=>{if(e.target.id==='route-select'){routeChoice=e.target.value;person().routeId=routeChoice;save();render();$('#travel-plan')?.scrollIntoView({block:'start'});}});
document.addEventListener('input',e=>{if(e.target.dataset.note){person().notes[e.target.dataset.note]=e.target.value;save();}});
document.addEventListener('submit',e=>{
 if(e.target.id==='settings-form'){e.preventDefault();const f=new FormData(e.target),budget=f.get('budget');state.settings={days:Number(f.get('days')),travelDays:Number(f.get('travelDays')),maxBases:Number(f.get('maxBases')),budget:budget===''?null:Number(budget)};state=validateSession(state);routeChoice=null;save();$('#dialog').close();render();toast('已按新的时间条件调整。');}
 if(e.target.id==='profiles-form'){e.preventDefault();const f=new FormData(e.target);state.profiles.forEach((p,i)=>p.name=String(f.get('name'+i)).trim()||`填写人${i+1}`);save();render();profilesDialog();}
});
let windowPendingImport=null;
function receiveImport(text){try{if(text.length>100000)throw new Error('备份过大，请选择本网页导出的答案备份。');windowPendingImport=validateSession(JSON.parse(text));modal('怎样使用这份手记',`<p>导入文件当前填写人：${escape(windowPendingImport.profiles[windowPendingImport.active].name)}。</p><div class="storage-actions"><button class="primary" data-action="merge-friend">作为另一位同行人的答案汇总</button><button class="secondary" data-action="restore-backup">用这份完整备份恢复两人的答案</button></div><p>合并时保留本机旅行条件；恢复完整备份会替换本机当前两份答案。</p>`);}catch(err){windowPendingImport=null;toast(err instanceof SyntaxError?'无法读取 JSON，原有答案没有改变。':err.message);}}
$('#import-input').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;if(file.size>100000){toast('文件过大，请选择本网页导出的 JSON 答案备份。');return;}receiveImport(await file.text());});
render();
initAnalytics();
