import {regions} from './regions.js';
import {scenes,regionById,axisNames,questionMap,blankSession,flowFor,selectedFor,recommend,itineraryFor,validateSession,compareProfiles,mirrorFor} from './journey.js';
const $=s=>document.querySelector(s);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='caiyun-web-journey-v2';
let state=blankSession(),routeChoice=null,saveFailed=false;
try{const saved=localStorage.getItem(key);if(saved)state=validateSession(JSON.parse(saved));}catch{saveFailed=true;}
const person=()=>state.profiles[state.active];
const img=(id,cls='',lazy=true)=>scenes[id]?.image?`<img class="${cls}" src="assets/${scenes[id].image}.webp" alt="${escape(scenes[id].sub)}情境插画，非真实照片" ${lazy?'loading="lazy"':'fetchpriority="high"'} decoding="async">`:`<img class="${cls} atlas-crop ${id}" src="assets/yunnan-atlas.webp" alt="云南风物艺术图鉴，非实景照片" loading="lazy">`;
function save(){try{localStorage.setItem(key,JSON.stringify(state));saveFailed=false;}catch{saveFailed=true;toast('此浏览器无法保存，请通过“保存与导出”下载手记。');}}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('visible'),3800);}
function modal(title,body,wide=false){$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=body;$('#dialog').classList.toggle('wide',wide);if(!$('#dialog').open)$('#dialog').showModal();}
function navigate(view){state.view=view;routeChoice=null;save();render(true);}
function activeResult(){return recommend(person(),state.settings);}
function render(top=false){
  $('#profile-name').textContent=person().name||'我';$('#avatar').textContent=(person().name||'我').slice(0,1);
  document.body.dataset.view=state.view;
  if(state.view==='journey'&&person().focus===null)state.view='home';
  const renders={home:home,journey:journey,results:results,compare:compare};
  $('#main').innerHTML=(renders[state.view]||home)();
  if(top){window.scrollTo({top:0,behavior:'instant'});$('#main').focus({preventScroll:true});}
}
function sceneCard(id,small=false){return `<button class="scene-card ${small?'small':''}" data-action="choose-scene" data-id="${id}">${img(id,'',id!=='dali')}<span class="scene-card-copy"><small>${escape(scenes[id].sub)}</small><strong>${escape(scenes[id].title)}</strong><span class="scene-entry">走进这个下午 <span aria-hidden="true">↗</span></span></span></button>`;}
function home(){const p=person(),count=selectedFor(p).filter(x=>x.option).length;return `
<section class="opening">
 <div class="opening-copy"><div class="chapter-line"><span>从心动开始</span><span>2026 / 国庆</span></div><h1>去云南，<br>你想过<br>哪一种日子？</h1><p class="lead">先不急着选城市。<br>哪一个画面，让你想走进去？</p><p class="intro-note">我们会沿着这份心动多问几句，<br>慢慢分清：想得到什么，也愿意放下什么。</p>
 ${count?`<div class="resume"><span>上次已经看清 ${count} 件事</span><button class="primary" data-action="resume">接着上次的想法</button></div>`:''}
 <button class="text-link" data-action="choose-scene" data-id="unknown">还说不清，从一种感受开始 <span>↗</span></button><div class="private-note">不用登录 · 回答只留在此浏览器</div></div>
 <div class="first-scenes">${sceneCard('dali')}${sceneCard('shangrila')}${sceneCard('mangshi')}</div>
</section>
<section class="more-scenes"><div class="section-line"><h2>也可能，是这样的一天</h2><span>不必全选，先跟着直觉走</span></div><div class="scene-strip">${['jianshui','kunming','fuxian','lijiang'].map(id=>sceneCard(id,true)).join('')}</div><p class="art-caption">场景为原创情境插画，非真实照片；晴空、花木与水色不代表国庆实景。</p></section>
 <section class="atlas-invite"><img src="assets/yunnan-atlas.webp" alt="云南山水风物艺术图鉴" loading="lazy"><div><h2>如果还不知道<br>云南有多少种样子。</h2><p>从雪山峡谷，到高原湖泊、梯田与雨林。把地理、吃食与地方生活先放到眼前。</p><button class="secondary" data-action="atlas">展开云南风物图鉴</button></div></section><section class="inspiration-section"><div class="section-line"><h2>云南，还可以把你好奇的事放大</h2><span>延伸灵感 · 不自动加入这次路线</span></div><div class="inspiration-grid"><button data-action="inspiration" data-id="tea"><span>普洱 · 景迈山</span><h3>一杯茶，<br>从哪一种生活里长出来？</h3><p>茶林、森林与村寨的关系。</p></button><button data-action="inspiration" data-id="terrace"><span>红河 · 元阳</span><h3>如果没有水镜，<br>你还想看什么？</h3><p>田埂、山势，和仍在发生的农事。</p></button><button data-action="inspiration" data-id="gorge"><span>滇西北 · 怒江</span><h3>如果一路在移动，<br>沿途能不能就是目的？</h3><p>峡谷、江水与村寨不断变换的关系。</p></button></div></section>`;}
function journey(){
  const p=person(),flow=flowFor(p);p.cursor=Math.min(p.cursor,flow.length-1);
  const q=flow[p.cursor],picked=p.answers[q.id],option=q.options.find(o=>o.id===picked),sceneId=q.id==='mirror'?(scenes[p.focus]?p.focus:'dali'):q.scene;
  const s=scenes[sceneId],known=selectedFor(p).filter(x=>x.option&&x.option.id!=='unknown').length;
  const progress=Math.round((p.cursor+1)/flow.length*100);
  let options=q.id==='contrast'?q.options.filter(o=>o.id!==p.focus):q.options;
  if(q.id==='anchor')options=q.options.filter(o=>!(o.id==='primary'&&!regionById[p.focus])&&!(o.id==='contrast'&&(!regionById[p.answers.contrast]||p.answers.contrast===p.focus))).map(o=>{const id=o.id==='primary'?p.focus:o.id==='contrast'?p.answers.contrast:null;const pull=questionMap[id+'_pull'];const chosen=pull?.options.find(x=>x.id===p.answers[pull.id]);return id?{...o,label:chosen&&chosen.id!=='unknown'?chosen.label:scenes[id].title,detail:regionById[id].name+'里的这份期待；如果没有，会更遗憾。'}:o;});
  return `<div class="journey-top"><button class="text-link" data-action="back">${p.cursor?'上一段':'重新看场景'}</button><div class="chapter-progress"><span>${escape(q.stage)}</span><div><i style="width:${progress}%"></i></div><span>已留下 ${known} 个线索</span></div><button class="text-link" data-action="results">先看愿望草图</button></div>
  <section class="journey-layout">
  <aside class="scene-stage"><div class="scene-visual">${img(sceneId,'scene-image',false)}<button class="image-detail" data-action="region" data-id="${sceneId}">认识${regionById[sceneId].name}</button><div class="scene-overlay"><span>${escape(s.sub)}</span><h2>${escape(s.title)}</h2></div></div><div class="sensory"><p>${escape(s.sensory)}</p><div class="scene-facts"><span>${escape(regionById[sceneId].food)}</span><button data-action="region" data-id="${sceneId}">这一天的细节</button></div><small>情境插画，非实景或当季景观承诺</small></div></aside>
  <article class="conversation"><div class="question-heading"><span class="question-number">${String(p.cursor+1).padStart(2,'0')}</span><span>把向往说具体</span></div><h1>${escape(q.title)}</h1><p class="question-context">${escape(q.context)}</p>
  ${q.id==='mirror'?`<blockquote class="mirror-draft">${escape(mirrorFor(p).text)}</blockquote>`:''}
  ${q.id==='transfer'?timeRibbon():''}
  <div class="options ${q.id==='contrast'?'contrast-options':''}" role="group" aria-label="${escape(q.title)}">${options.map((o,i)=>`<button class="option ${picked===o.id?'chosen':''} ${o.id==='unknown'?'unknown-option':''}" data-action="answer" data-question="${q.id}" data-id="${o.id}" aria-pressed="${picked===o.id}">${q.id==='contrast'&&scenes[o.id]?img(o.id,'option-thumb'):''}<span class="option-index">${picked===o.id?'✓':o.id==='unknown'?'…':String.fromCharCode(65+i)}</span><span><strong>${escape(o.label)}</strong><small>${escape(o.detail)}</small></span></button>`).join('')}</div>
  ${option?`<div class="response" aria-live="polite"><span class="response-mark">云</span><p>${escape(option.echo||'这个答案已记下。我们继续让它更具体一点。')}</p></div>`:''}
  <details class="your-words" ${p.notes[q.id]?'open':''}><summary>也想用自己的话补一句</summary><label for="note">你的原话会保留在手记里，不自动归类或打分。</label><textarea id="note" data-note="${q.id}" maxlength="500" rows="3" placeholder="也许还有一种选项，没有写出我的感觉……">${escape(p.notes[q.id]||'')}</textarea></details>
  <div class="conversation-foot"><small>${saveFailed?'请导出备份，以免丢失':'已自动保存在此浏览器'}</small><button class="primary" data-action="next" ${!picked?'disabled':''}>${p.cursor===flow.length-1?'整理这次的向往':'沿着这个想法，再往下看看'} <span aria-hidden="true">↗</span></button></div>
  </article></section>`;
}
function timeRibbon(){const n=state.settings.days;return `<div class="time-ribbon"><div><strong>${n} 天，不是 ${n} 个完整游玩日</strong><button data-action="settings">调整天数</button></div><div class="day-boxes">${Array.from({length:n},(_,i)=>`<span class="${i===0||i===n-1?'travel':'stay'}">${i===0?'到达':i===n-1?'返程':'停留'}</span>`).join('')}</div><small>每增加一次跨地区换住，再拿走一个“停留”格。</small></div>`;}
function evidencePanel(result){const p=person(),mirror=mirrorFor(p),mainAxis=result.axes[0];return `<section class="wish-note"><div class="section-line"><h2>关于这次的你，我先这样记下</h2><button class="text-link" data-action="edit-question" data-id="mirror">确认或纠正</button></div>
<div class="wish-grid"><div class="wish-main"><span class="tag">${mirror.confirmed?'你已确认的理解':p.answers.mirror==='change'?'你希望重新澄清':'等待你确认的理解'}</span><p>${escape(p.answers.mirror==='change'?'你没有完全认同之前的复述。下面保留原答案，建议还需要按你的意思修正。':mirror.text)}</p>${p.answers.mirror==='change'&&p.answers.clarify&&p.answers.clarify!=='unknown'?`<p>你后来明确想保住的是：<strong>${escape(questionMap.clarify.options.find(o=>o.id===p.answers.clarify).label)}</strong>。</p>`:''}${result.protectedRegion?`<div class="protected-wish"><strong>你最不想删掉：${regionById[result.protectedRegion].name}里的那份体验</strong><p>${result.ranked.find(d=>d.id===result.protectedRegion).excluded?'但它和你当前的排除或高原边界冲突。先保留这份向往，不强行编排行程。':'时间草案会优先保留它。较高的平均分不等于可以替你放弃。'}</p><button class="text-link" data-action="edit-question" data-id="anchor">重新看看这个取舍</button></div>`:''}</div><div class="wish-axes"><h3>目前更有分量的线索</h3>${result.axes.slice(0,4).map(([axis,w])=>`<div><span>${axisNames[axis]}</span><i><b style="width:${Math.round(w/mainAxis[1]*100)}%"></b></i></div>`).join('')}<small>表示所选线索的相对分量，不是人格比例。</small></div></div>
<div class="evidence-list">${result.selected.filter(x=>x.option&&x.option.id!=='unknown'&&x.option.echo).slice(0,4).map(({question,option})=>`<div><span>${escape(question.title)}</span><strong>“${escape(option.label)}”</strong><button data-action="edit-question" data-id="${question.id}">改一处</button></div>`).join('')}</div></section>`;}
function results(){const p=person(),r=activeResult();if(!r.hasPreferences)return `<section class="empty-state"><h1>还不用急着得出答案。</h1><p>目前的回答还不足以形成一个方向。留下“不确定”没有关系，可以从一个更小的画面继续。</p><button class="primary" data-action="resume">回到场景，继续想想</button><button class="secondary" data-action="atlas">先认识云南</button></section>`;
 const route=r.available.find(t=>t.id===routeChoice)||r.primary,top=r.ranked.find(d=>!d.excluded),days=itineraryFor(route,r,state.settings);
 if(!top)return `<section class="empty-state"><h1>这次先没有合适的候选。</h1><p>你已排除全部地区。我们保留这些边界，不用低分候选凑一个结论。可以恢复一个想再看看的地方。</p><div class="button-row">${r.ranked.map(d=>p.excluded.includes(d.id)?`<button class="secondary" data-action="exclude" data-id="${d.id}">恢复${d.name}</button>`:`<button class="secondary" data-action="edit-question" data-id="altitude">重新考虑高原意愿</button>`).join('')}</div><button class="primary" data-action="home">重新看看云南的场景</button></section>`;
 const provisional=r.unknowns.length>0;
 return `<section class="result-hero">${img(top.id,'result-image',false)}<div class="result-hero-copy"><span class="result-kicker">${escape(p.name)}的云南愿望手记 · ${provisional?'仍可继续探索':'已经有了方向'}</span><h1>${escape(r.style)}</h1><p>它来自你刚才留下的 ${r.answered} 个线索。<br>目的地是回应这些期待的可能，而不是替你做完的决定。</p><div><button class="white-button" data-action="journal">带走这份手记</button><button class="glass-button" data-action="compare">和同行的人对照</button></div></div><span class="hero-art-note">情境插画，非真实照片</span></section>
 <div class="results-body">${evidencePanel(r)}
 <section class="destination-section"><div class="section-line"><div><h2>哪些云南，回应了这些期待</h2><p>先看理由，再看匹配分。明确不去的地方不参与推荐。</p></div><button class="text-link" data-action="rules">分数的来处</button></div><div class="destination-grid">${r.ranked.filter(d=>!d.excluded).slice(0,3).map((d,i)=>`<article class="destination"><button class="destination-photo" data-action="region" data-id="${d.id}">${img(d.id)}<span>${escape(d.region)}</span></button><div class="destination-copy"><div class="dest-title"><h3>${d.name}</h3><span><strong>${d.score}</strong><small>/ 100 偏好吻合</small></span></div><p>${escape(d.subtitle)}</p><ul>${d.evidence.slice(0,2).map(e=>`<li>你选了“${escape(e.answer)}”</li>`).join('')}</ul><div class="cost-note"><strong>也需要接受</strong><p>${escape(d.tradeoff)}</p>${d.conditional?'<p>高原意愿尚未确认，属于有条件候选。</p>':''}</div><div class="dest-actions"><button data-action="region" data-id="${d.id}">看一整天怎样过</button><button data-action="exclude" data-id="${d.id}">这次不选</button></div></div></article>`).join('')}</div><details class="all-candidates"><summary>展开全部 9 个候选与排除项</summary><div>${r.ranked.map(d=>`<div class="candidate-row"><span>${d.name}</span><span>${d.excluded?'已排除':d.score+' 分'}${d.conditional&&!d.excluded?' · 高原待确认':''}</span><button data-action="region" data-id="${d.id}">认识一下</button><button data-action="exclude" data-id="${d.id}">${p.excluded.includes(d.id)?'恢复候选':d.excluded?'按高原选择排除':'这次不选'}</button></div>`).join('')}</div></details></section>
 <section class="plan-section"><div class="section-line"><div><h2>把向往放进真正可用的时间里</h2><p>${state.settings.days} 个日历日 · 往返预留 ${state.settings.travelDays} 天 · ${r.pace==='restful'?'优先保住轻松':'每天一个重点'}${state.settings.budget!==null?' · 每人预算目标 '+state.settings.budget+' 元（未核价）':''}</p></div><button class="secondary" data-action="settings">调整旅行条件</button></div>
 <div class="route-choices">${[...new Map([...(r.primary?[r.primary]:[]),...r.available].map(t=>[t.id,t])).values()].map(t=>`<button data-action="route" data-id="${t.id}" class="${route?.id===t.id?'selected':''}"><strong>${escape(t.name)}</strong><span>${t.ids.length} 个基地 · ${t.moves} 次转场${t.conditional?' · 高原待确认':''}</span></button>`).join('')}</div>
 ${route?`<div class="plan-heading"><h3>${escape(route.name)}</h3><p>${escape(route.tradeoff)}${r.pace==='restful'?' 这份安排为每个基地保留至少两个完整活动日。':''}</p><div class="plan-stats"><span>${route.fullDays}<small>完整活动日</small></span><span>${route.moves}<small>整段转场日</small></span><span>${state.settings.days-1}<small>住宿夜数</small></span></div>${route.conditional?'<p class="notice">先明确是否接受高原环境，再决定这条路线。<button data-action="edit-question" data-id="altitude">继续确认</button></p>':''}</div><ol class="itinerary">${days.map(d=>`<li class="${d.type}"><span class="day-number">D${d.day}</span><div><small>${d.type==='stay'?'只设一个重点':d.type==='transfer'?'这天也是旅行成本':'留给交通'}</small><h4>${escape(d.title)}</h4><p>${escape(d.detail)}</p></div><span class="overnight">${d.overnight?'住 '+regionById[d.base].name:'回家'}</span></li>`).join('')}</ol>`:'<p class="notice">目前的天数、排除项和换住上限，没有形成合适的组合。先放宽一项，或保留未知继续讨论。</p>'}
 <p class="plan-limit">这是时间分配草案。班次、实际交通耗时、票价、住宿和门票尚未查询；预算目标不等于已经可实现。跨方向长途若超出预留日，需要重新编排。</p></section>
 ${r.unknowns.length?`<section class="unresolved"><h2>还没有被说清楚的，也带走</h2><p>这些空白不会被当成默认同意。</p><div>${r.unknowns.slice(0,5).map(q=>`<button data-action="edit-question" data-id="${q.id}">${escape(q.title)} <span>继续想想 ↗</span></button>`).join('')}</div></section>`:''}
 <section class="closing-note"><h2>看完建议，你最想改哪一处？</h2><p>好的理解应当允许被你纠正。你随时可以回到愿望、节奏，或另一种云南。</p><div><button class="secondary" data-action="edit-question" data-id="need">我想要的还没说准</button><button class="secondary" data-action="edit-question" data-id="rest">这个节奏不太像我</button><button class="secondary" data-action="home">另一个画面也想看看</button></div></section></div>`;
}
function compare(){const c=compareProfiles(state);return `<div class="compare-page"><div class="section-line"><div><span class="tag">一起去，也可以有不同向往</span><h1>先各自回答，再找共同的一天。</h1><p>保留两个人的愿望，不把“不愿意”平均掉。</p></div><button class="secondary" data-action="profiles">切换填写人</button></div><div class="people-grid">${state.profiles.map((p,i)=>`<article><span class="avatar large">${escape(p.name.slice(0,1)||'旅')}</span><h2>${escape(p.name)}</h2><p>${c.results[i].hasPreferences?escape(c.results[i].style):'还没有留下足够的线索'}</p><div>${c.results[i].ranked.filter(r=>!r.excluded).slice(0,3).map(r=>c.results[i].hasPreferences?`<span class="tag">${r.name} ${r.score}</span>`:'').join('')}</div><button class="primary" data-action="switch" data-id="${i}">${i===state.active?'继续我的探索':'切换并独立填写'}</button></article>`).join('')}</div>
${c.bothReady?`<section><h2>目前可以一起讨论的方向</h2><p>共同分优先照顾较不心动的一方；任何一方明确排除的地区，均不会成为共同推荐。它仍不是你们已作出的决定。</p><div class="shared-candidates">${c.common.filter(x=>!x.excluded).slice(0,3).map(x=>`<button data-action="region" data-id="${x.region.id}">${img(x.region.id)}<strong>${x.region.name}</strong><span>${escape(state.profiles[0].name)} ${x.values[0].score} / ${escape(state.profiles[1].name)} ${x.values[1].score}</span></button>`).join('')}</div></section><section class="differences"><h2>真正需要聊一聊的是这些</h2>${c.differences.length?c.differences.map(id=>`<article><h3>${escape(questionMap[id].title)}</h3>${state.profiles.map(p=>`<p><strong>${escape(p.name)}</strong>：${escape(questionMap[id].options.find(o=>o.id===p.answers[id]).label)}</p>`).join('')}<p class="gentle">先各说一个“如果这点没被满足，我会遗憾”的具体半天，再看能否安排到同一个基地。</p></article>`).join(''):'<p>已回答的关键选择暂未发现明显分歧；未回答的部分仍需各自确认。</p>'}</section>`:`<div class="empty-state"><h2>另一份真实答案，比猜测同伴更有用。</h2><p>可以在这台设备切换填写人；也可以请朋友在自己的设备答完后导出手记，再从“保存与导出”合并朋友的答案。</p></div>`}</div>`;}
function regionDialog(id){const r=regionById[id],s=scenes[id];modal(r.name+'，不止一个地名',`<div class="region-cover">${img(id,'',false)}<span>${escape(s.sub)}</span></div><p class="region-story">${escape(s.sensory)}</p><div class="region-detail-grid"><section><h3>一天，可以这样过</h3>${r.activities.map(a=>`<p><strong>${escape(a.title)}</strong><br>${escape(a.detail)}</p>`).join('')}</section><section><h3>把味道记具体</h3><p>${escape(r.food)}</p><h3>也要接受</h3><p>${escape(r.tradeoff)}</p><h3>十月，不替风景作保证</h3><p>${escape(r.season)}</p></section></div><div class="region-question"><p>${escape(s.hook)}</p><button class="primary" data-action="choose-scene" data-id="${id}">从这里开始探寻</button></div><details><summary>地理与资料依据</summary><p>${escape(r.region)} · 城区或区域参考海拔约 ${r.altitude} 米，景区具体位置不同。</p>${r.sources.map(x=>`<p><a href="${escape(x.url)}" target="_blank" rel="noopener noreferrer">${escape(x.title)}</a></p>`).join('')}<p>插画是场景想象，不是地理比例图或实景照片。</p></details>`,true);}
function settingsDialog(){const s=state.settings;modal('给这次旅行留多大空间',`<form id="settings-form"><label>总日历天数（含去回）<select name="days">${[3,4,5,6,7,8,9].map(n=>`<option ${s.days===n?'selected':''} value="${n}">${n} 天</option>`).join('')}</select></label><label>往返交通总预留<select name="travelDays"><option value="2" ${s.travelDays===2?'selected':''}>2 天，去回各一天</option><option value="1" ${s.travelDays===1?'selected':''}>1 天，只有已核实两端各半天才选</option></select></label><label>最多几个住宿基地<select name="maxBases">${[1,2,3].map(n=>`<option value="${n}" ${s.maxBases===n?'selected':''}>${n} 个基地，${n-1} 次换住</option>`).join('')}</select></label><label>每人预算目标（元，可留空）<input name="budget" type="number" min="0" max="1000000" step="1" value="${s.budget??''}" placeholder="暂时没定"></label><p>预算只记录目标，没有实时查询价格。转场会另外占用日程；选择“往返合计一天”也不增加完整停留日，只可能保留到达/返程的半天。</p><button class="primary" type="submit">按这些条件重新看安排</button></form>`);}
function journalAnswerLabel(p,q,o){
 if(q.id!=='anchor'||!['primary','contrast'].includes(o.id))return o.label;
 const id=o.id==='primary'?p.focus:p.answers.contrast,pull=questionMap[id+'_pull'],picked=pull?.options.find(x=>x.id===p.answers[pull.id]);
 return regionById[id]?regionById[id].name+'：'+(picked&&picked.id!=='unknown'?picked.label:scenes[id].title):o.label;
}
function journalText(){const p=person(),r=activeResult(),route=r.available.find(t=>t.id===routeChoice)||r.primary;return `心向彩云 · ${p.name}的云南愿望手记\n${new Date().toLocaleDateString('zh-CN')}\n\n这次更像：${r.style}\n理解状态：${p.answers.mirror==='yes'?'本人已确认':p.answers.mirror==='change'?'本人希望修正':'待本人确认'}\n${p.answers.mirror==='change'?'之前的复述已撤回，以我后来确认的答案和原话为准。':mirrorFor(p).text}\n\n${r.selected.filter(x=>x.option).map(({question,option})=>`${question.title}\n${journalAnswerLabel(p,question,option)}${p.notes[question.id]?'\n我的原话：'+p.notes[question.id]:''}`).join('\n\n')}\n\n旅行条件：${state.settings.days}个日历日；往返预留${state.settings.travelDays}天；最多${state.settings.maxBases}个住宿基地。\n预算目标：${state.settings.budget===null?'未定':state.settings.budget+'元/人，未核报价'}\n\n${r.hasPreferences?'候选：'+r.ranked.filter(x=>!x.excluded).slice(0,3).map(x=>x.name+' '+x.score+'分').join('；'):'还没有足够线索形成方向'}\n${route?'时间草案：'+route.name+'\n'+itineraryFor(route,r,state.settings).map(d=>'D'+d.day+' '+d.title+'：'+d.detail).join('\n'):''}\n\n待确认：${r.unknowns.map(q=>q.title).join('；')||'交通、天气、开放与实际报价'}\n这是偏好规则生成的探索草案，不是人格测评或已经预订的行程。自由文字原样保留，未被自动理解或打分。`;}
function journalDialog(){modal('把这一刻的想法带走',`<p>可以复制给同行的人继续聊，也可以下载留存。自由补充会以你的原话出现。</p><textarea class="journal-text" readonly aria-label="旅行手记全文">${escape(journalText())}</textarea><div class="button-row"><button class="primary" data-action="copy-journal">复制手记</button><button class="secondary" data-action="download-journal">下载文字版</button><button class="secondary" data-action="export">导出可恢复的答案</button></div>`);}
function download(name,text,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function storageDialog(){modal('保存、导出与两人汇总',`<p>选择会自动保存在当前浏览器。更换设备、无痕浏览或清理浏览数据可能使它丢失；下载一份 JSON 就能恢复。</p><div class="storage-actions"><button class="primary" data-action="export">下载完整答案备份</button><button class="secondary" data-action="import">导入备份或朋友的答案</button><button class="secondary" data-action="paste-import">粘贴备份文字来恢复</button><button class="secondary" data-action="journal">复制／下载我的文字手记</button></div><p class="notice">答案与自由文字只保存在设备中，不会作为问卷数据上传；托管服务仍会处理网页访问的常规请求。暂不提供云端同步。</p><button class="text-link danger" data-action="reset-prompt">重新开始当前填写人的探索</button>`);}
function profilesDialog(){modal('谁在回答这一轮',`<p>先各自回答，再一起对照。姓名只是本机的区分标签，可以用昵称。</p><form id="profiles-form">${state.profiles.map((p,i)=>`<label>填写人 ${i+1}<input name="name${i}" maxlength="20" value="${escape(p.name)}" required></label>`).join('')}<button class="secondary" type="submit">保存称呼</button></form><div class="button-row">${state.profiles.map((p,i)=>`<button class="${i===state.active?'primary':'secondary'}" data-action="switch" data-id="${i}">${escape(p.name)}${i===state.active?' · 正在填写':''}</button>`).join('')}</div>`);}
function sourcesDialog(){modal('云南很具体，想象也需要边界',`<p>核心匹配目前覆盖下列 9 个地区。资料核对于 2026 年 9 月；历史介绍用于认识地方特色，不代表国庆期间开放、票价与景观保证。</p>${regions.map(r=>`<section class="source-region"><h3>${r.name}</h3><p>${escape(r.season)}</p>${r.sources.map(s=>`<a href="${escape(s.url)}" target="_blank" rel="noopener noreferrer">${escape(s.title)}</a>`).join('')}</section>`).join('')}<p>原图鉴覆盖云南 16 个州市。图鉴元素是全年艺术示意，不能直接当成本次国庆可以同时看到的景观。所有场景插画均非真实照片。</p>`,true);}
function rulesDialog(){modal('建议如何从你的答案里长出来',`<ol class="rules-list"><li><strong>先记录，不急着定义。</strong>场景的第一眼吸引与后续具体选项一起保存。复述只有得到你的确认，才标成“已确认”。自由文字原样保留，不自动打分。</li><li><strong>匹配的是这次的愿望。</strong>山川、湖岸、文化、吃食、休息、陌生感、手作、植物、街头生活各有选项权重。地区特征用 1—5 的编辑评分，按你选择的权重算平均，再换算为 100 分；首选场景加 4 分。</li><li><strong>代价不会被平均掉。</strong>避开高原或明确不去优先于分数；不想依赖天气时，丽江和香格里拉减 5 分。明确改选稳定方向再减 8 分。未知高原意愿只给有条件候选。</li><li><strong>城市越多不自动得分越高。</strong>你明确最不想删掉的地区体验优先保留，但不越过排除与高原边界。其余组合取目的地均分，每次转场再扣 4 分（慢住扣 6 分）。每次转场保守预留一个日程格；慢住每基地至少两个完整活动日。夜数始终等于日历天数减一。</li><li><strong>两个人，先尊重底线。</strong>任一方排除的地区不参与共同建议；共同分为较低个人分的 70% 加个人均分的 30%。它用来开启讨论，不表示已经达成共识。</li><li><strong>没有“心理准确率”。</strong>这些是可解释的编辑规则，不是临床心理量表、读心结果或满意度预测。交通、价格与预约需要另查。</li></ol>`);}
function editQuestion(id){const p=person();if(p.focus===null)p.focus='unknown';if(id==='altitude'&&!flowFor(p).some(q=>q.id==='altitude')){modal('高原意愿',`<p>此项会影响香格里拉候选，也会影响丽江高处项目。</p>${questionMap.altitude.options.map(o=>`<button class="option" data-action="direct-altitude" data-id="${o.id}"><span><strong>${escape(o.label)}</strong><small>${escape(o.detail)}</small></span></button>`).join('')}`);return;}p.cursor=Math.max(0,flowFor(p).findIndex(q=>q.id===id));$('#dialog').close();navigate('journey');}
document.addEventListener('click',async e=>{
 const el=e.target.closest('[data-action]');if(!el)return;const {action,id,question}=el.dataset;const p=person();
 if(action==='close'){$('#dialog').close();return;}
 if(action==='home'){navigate('home');return;}
 if(action==='choose-scene'){if(p.focus!==id){delete p.answers.mirror;delete p.answers.clarify;}p.focus=id;p.cursor=0;p.complete=false;$('#dialog').close();navigate('journey');return;}
 if(action==='answer'){const f=flowFor(p);if(p.answers[question]!==id&&f.findIndex(q=>q.id===question)<f.findIndex(q=>q.id==='mirror')){delete p.answers.mirror;delete p.answers.clarify;}p.answers[question]=id;save();render();return;}
 if(action==='next'){const f=flowFor(p);if(!p.answers[f[p.cursor].id])return;if(p.cursor<f.length-1){p.cursor++;save();render(true);}else{p.complete=true;navigate('results');}return;}
 if(action==='back'){if(p.cursor){p.cursor--;save();render(true);}else navigate('home');return;}
 if(action==='resume'){navigate(p.focus?'journey':'home');return;}
 if(action==='results'){navigate('results');return;}
 if(action==='compare'){navigate('compare');return;}
 if(action==='profiles'){profilesDialog();return;}
 if(action==='switch'){state.active=Number(id);$('#dialog').close();navigate(person().focus?'journey':'home');return;}
 if(action==='region'){regionDialog(id);return;}
 if(action==='settings'){settingsDialog();return;}
 if(action==='route'){routeChoice=id;render();$('#main .plan-section')?.scrollIntoView({block:'start'});return;}
 if(action==='edit-question'){editQuestion(id);return;}
 if(action==='direct-altitude'){p.answers.altitude=id;save();$('#dialog').close();render();return;}
 if(action==='exclude'){const ix=p.excluded.indexOf(id);if(ix<0)p.excluded.push(id);else p.excluded.splice(ix,1);routeChoice=null;save();render();return;}
 if(action==='journal'){journalDialog();return;}
 if(action==='copy-journal'){try{await navigator.clipboard.writeText(journalText());toast('手记已复制。');}catch{const t=$('.journal-text');t?.select();toast('浏览器限制了复制，请复制已选中的手记文字。');}return;}
 if(action==='download-journal'){download('心向彩云-旅行手记.txt',journalText());toast('已开始下载文字手记。');return;}
 if(action==='storage'){storageDialog();return;}
 if(action==='export'){const text=JSON.stringify(state,null,2);download('心向彩云-答案备份.json',text,'application/json');modal('答案备份：下载或复制都可以',`<p>已向浏览器发起下载。如果内置浏览器没有出现文件，可复制下方备份文字保存；以后从“粘贴备份文字来恢复”导入。</p><textarea class="journal-text" id="backup-text" readonly aria-label="JSON答案备份">${escape(text)}</textarea><div class="button-row"><button class="primary" data-action="copy-backup">复制备份文字</button><button class="secondary" data-action="download-backup">再次下载 JSON</button></div>`);return;}
 if(action==='download-backup'){download('心向彩云-答案备份.json',JSON.stringify(state,null,2),'application/json');toast('已向浏览器发起下载；没有文件时，可复制备份文字。');return;}
 if(action==='copy-backup'){try{await navigator.clipboard.writeText(JSON.stringify(state,null,2));toast('备份文字已复制，可以私下发给同行人或保存在备忘录。');}catch{$('#backup-text')?.select();toast('请手动复制已选中的备份文字。');}return;}
 if(action==='paste-import'){modal('粘贴完整的答案备份',`<p>粘贴从本网页复制的 JSON 备份。确认格式后，你仍可选择合并朋友的答案或恢复两人的备份。</p><textarea class="journal-text" id="paste-backup" aria-label="粘贴JSON备份" placeholder="把完整备份文字粘贴到这里"></textarea><button class="primary" data-action="parse-backup">读取这份备份</button>`);return;}
 if(action==='parse-backup'){receiveImport($('#paste-backup').value);return;}
 if(action==='import'){$('#import-input').value='';$('#import-input').click();return;}
 if(action==='rules'){rulesDialog();return;}
 if(action==='sources'){sourcesDialog();return;}
 if(action==='inspiration'){const cards={tea:{name:'景迈山：把一杯茶放回它生长的地方',text:'茶树与高树共同生长，传统村寨与茶林相邻。你可以好奇的，不只是哪杯好喝，还有为什么在林下种茶、茶林和生活怎样相处。这里需要单独安排山区进出和接待，不能当作普洱市区顺路停一下。',ask:'如果没有采茶体验，也没有拍到云海，只是看茶林、喝茶、听懂一点村寨生活，你还愿意专程留时间吗？',source:'https://whc.unesco.org/en/list/1665',sourceName:'UNESCO 景迈山古茶林文化景观'},terrace:{name:'元阳：漂亮画面背后的土地与生活',text:'森林、水系、村寨和梯田共同构成持续运作的农业景观。你可以为图案与光线而来，也可以看看人们怎样在山地生活。元阳需要独立安排山区交通；它不是建水市内的一个景点。',ask:'如果田里是当时真实的农事状态，而不是照片里的水镜或金黄，你还想看什么：田埂山势、村寨生活，还是决定等特定季节再来？',source:'https://whc.unesco.org/en/list/1111',sourceName:'UNESCO 红河哈尼梯田文化景观'},gorge:{name:'怒江：沿途也可以是旅行的内容',text:'沿江向前，水声与两岸山势不断改变位置，公路连接村寨和观景点。较长的公路移动本身就是体验的一部分；是否适合，要先看你愿不愿意把时间交给路。',ask:'如果一天有较多时间坐车，换来的是不断变化的峡谷风景，你更想沿路前行，还是到一个喜欢的地方住下来？',source:'https://jtyst.yn.gov.cn/xyxw/202601/t20260105_3431033.html',sourceName:'云南省交通运输厅：怒江美丽公路'}};const d=cards[id];modal(d.name,`<span class="tag">延伸灵感 · 暂不参与核心匹配</span><p class="region-story">${escape(d.text)}</p><blockquote class="mirror-draft">${escape(d.ask)}</blockquote><p>先把这份好奇记住，再另核交通、季节与时间。本页不保证采茶、云海、梯田水镜或具体道路条件。</p><p><a href="${d.source}" target="_blank" rel="noopener noreferrer">${d.sourceName}</a></p><button class="secondary" data-action="atlas">看看它在云南哪里</button>`);return;}
 if(action==='atlas'){modal('云南山水风物图鉴',`<p>先看方位，再看风物。图鉴为全年艺术示意；不代表国庆能同时看到所有景观。</p><iframe class="atlas-frame" src="atlas.html" title="云南16州市可缩放互动风物地图"></iframe><div class="button-row">${regions.map(r=>`<button class="secondary" data-action="region" data-id="${r.id}">${r.name}的一天</button>`).join('')}</div>`,true);return;}
 if(action==='reset-prompt'){modal('重新开始这位填写人的探索',`<p>只重置“${escape(p.name)}”的当前答案。可先下载备份，另一位的答案会保留。</p><div class="button-row"><button class="secondary" data-action="export">先下载备份</button><button class="primary" data-action="reset">确认重新开始</button></div>`);return;}
 if(action==='reset'){const name=p.name;state.profiles[state.active]=blankSession().profiles[0];person().name=name;$('#dialog').close();navigate('home');return;}
 if(action==='restore-backup'){state=windowPendingImport;windowPendingImport=null;$('#dialog').close();save();render(true);toast('已恢复这份备份。');return;}
 if(action==='merge-friend'){const incoming=windowPendingImport.profiles[windowPendingImport.active];state.profiles[1-state.active]=incoming;windowPendingImport=null;$('#dialog').close();save();navigate('compare');toast('已导入对方当前填写人的答案。');return;}
});
document.addEventListener('input',e=>{if(e.target.dataset.note){person().notes[e.target.dataset.note]=e.target.value;save();}});
document.addEventListener('submit',e=>{
 if(e.target.id==='settings-form'){e.preventDefault();const f=new FormData(e.target),budget=f.get('budget');state.settings={days:Number(f.get('days')),travelDays:Number(f.get('travelDays')),maxBases:Number(f.get('maxBases')),budget:budget===''?null:Number(budget)};state=validateSession(state);routeChoice=null;save();$('#dialog').close();render();toast('已按新的时间条件调整。');}
 if(e.target.id==='profiles-form'){e.preventDefault();const f=new FormData(e.target);state.profiles.forEach((p,i)=>p.name=String(f.get('name'+i)).trim()||`填写人${i+1}`);save();render();profilesDialog();}
});
let windowPendingImport=null;
function receiveImport(text){try{if(text.length>100000)throw new Error('备份过大，请选择本网页导出的答案备份。');windowPendingImport=validateSession(JSON.parse(text));modal('怎样使用这份手记',`<p>导入文件当前填写人：${escape(windowPendingImport.profiles[windowPendingImport.active].name)}。</p><div class="storage-actions"><button class="primary" data-action="merge-friend">作为另一位同行人的答案汇总</button><button class="secondary" data-action="restore-backup">用这份完整备份恢复两人的答案</button></div><p>合并时保留本机旅行条件；恢复完整备份会替换本机当前两份答案。</p>`);}catch(err){windowPendingImport=null;toast(err instanceof SyntaxError?'无法读取 JSON，原有答案没有改变。':err.message);}}
$('#import-input').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;if(file.size>100000){toast('文件过大，请选择本网页导出的 JSON 答案备份。');return;}receiveImport(await file.text());});
render();
