import {regionById,scenes} from './journey.js?v=20260927-4';
import {sceneImage} from './media.js?v=20260927-4';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const classicRoutes=[
 {id:'dali',ids:['dali'],label:'大理',mood:'苍山洱海，慢慢住',hook:'同样是大理，你想环海看风景，还是在喜洲的街边坐下来？',tags:'苍山 · 洱海 · 喜洲 · 周城',cost:'少换住，仍要取舍环湖距离与热门街区的人流。',region:'湖岸与白族生活'},
 {id:'dali-lijiang',ids:['dali','lijiang'],label:'大理 → 丽江',mood:'湖岸、古镇与雪山',hook:'你舍不得的是洱海的松弛，还是玉龙雪山和白沙的那一眼？',tags:'洱海 · 白沙 · 玉龙雪山',cost:'需要换一次住；雪山预约、天气与高处活动要另作决定。',region:'经典双城'},
 {id:'dali-lijiang-shangrila',ids:['dali','lijiang','shangrila'],label:'大理 → 丽江 → 香格里拉',mood:'从洱海走向藏地',hook:'三个都心动。你愿意把多少假期交给换住和转场？',tags:'洱海 · 雪山 · 独克宗 · 松赞林',cost:'需要两次换住；七天草案每地只剩一个完整活动日，不能同时期待深游和躺平。',region:'大丽香经典线'},
 {id:'lijiang-shangrila',ids:['lijiang','shangrila'],label:'丽江 → 香格里拉',mood:'山下的日常，高原的辽阔',hook:'喜欢经幡与藏地生活，还是草甸、湖泊和开阔的天空？',tags:'白沙 · 独克宗 · 纳帕海',cost:'一次换住，并需接受高原环境；寺院、草甸与峡谷不是一天的打卡清单。',region:'雪山与藏地'},
 {id:'xishuangbanna',ids:['xishuangbanna'],label:'西双版纳',mood:'植物、傣味与热带日常',hook:'想要夜市的热闹，还是认真认识一片雨林和一个村寨？',tags:'景洪 · 植物园 · 勐罕 · 傣味',cost:'植物园和村寨需要各自留时间；炎热、降雨与景区接驳都会影响节奏。',region:'热带云南'},
 {id:'kunming-fuxian-jianshui',ids:['kunming','fuxian','jianshui'],label:'昆明 → 抚仙湖 → 建水',mood:'春城、蓝湖与古城烟火',hook:'植物园的半天、湖边的留白、烤豆腐的炭火，哪段最不想删？',tags:'植物园 · 抚仙湖 · 古城 · 豆腐',cost:'走全线要两次换住；也可以只保留昆明＋抚仙湖，或昆明＋建水。',region:'湖泊与滇南风味'},
 {id:'mangshi-tengchong',ids:['mangshi','tengchong'],label:'芒市 → 腾冲',mood:'边城风味，温泉古镇',hook:'更想为陌生味道专程出门，还是留一个下午给温泉？',tags:'芒市小吃 · 和顺 · 温泉 · 地热',cost:'两地之间要留出公路转场；泡汤、地热观光和湿地是不同的一天。',region:'滇西双城'},
 {id:'dali-shangrila',ids:['dali','shangrila'],label:'大理 → 香格里拉',mood:'一半湖岸，一半藏地',hook:'如果跳过丽江，能不能把最想要的两种云南过得更完整？',tags:'苍山洱海 · 藏地生活 · 经幡',cost:'仍有一次跨地区转场；想两边都慢下来，要给足停留与高原适应余量。',region:'只保留最心动的两地'}
];
export const classicById=Object.fromEntries(classicRoutes.map(r=>[r.id,r]));
export function classicExplorer(){return `<section class="corridor-explorer" id="regional-routes"><div class="section-line"><div><span class="small-label">攻略里的地名，怎样变成你的假期</span><h2>大理、丽江、版纳……<br>哪条云南，才是你想去的？</h2><p>从你已经心动的地方或经典线路开始。我们再聊清楚：想留下什么，愿意付出什么。</p></div></div><div class="corridor-grid classic-grid">${classicRoutes.map(r=>`<button class="corridor-card classic-card" data-action="classic" data-id="${r.id}"><span class="classic-pictures count-${r.ids.length}">${r.ids.map(id=>sceneImage(id,{alt:regionById[id].name+'区域情境插画',sizes:'(max-width:520px) 320px, (max-width:1100px) 420px, 420px'})).join('')}<span class="classic-badge">${esc(r.region)}</span></span><span class="corridor-card-copy"><strong>${esc(r.label)}</strong><span class="classic-mood">${esc(r.mood)}</span><span>${esc(r.hook)}</span><span class="corridor-stops">${esc(r.tags)}</span><span class="corridor-open">看看哪一段让我心动 <b aria-hidden="true">↗</b></span></span></button>`).join('')}</div><div class="destination-shortcuts"><p>只想先了解一个地方？</p><div>${['dali','lijiang','shangrila','kunming','fuxian','jianshui','mangshi','tengchong','xishuangbanna'].map(id=>`<button data-action="region" data-id="${id}">${regionById[id].name}<span> ↗</span></button>`).join('')}</div></div></section>`;}
export function classicDialogBody(id){const r=classicById[id];if(!r)return '';return `<p class="region-story">${esc(r.hook)}</p><p>先从一个具体的画面聊起。选择这条线，只是把它放进待比较清单；最后也可能发现，少去一站更适合你。</p><div class="classic-scene-choices">${r.ids.map(base=>`<button data-action="classic-start" data-id="${base}" data-route="${id}">${sceneImage(base,{alt:regionById[base].name+'区域情境插画',sizes:'(max-width:650px) 90vw, 380px'})}<span><small>${regionById[base].name}</small><strong>${esc(scenes[base].title)}</strong><em>从这份心动开始 ↗</em></span></button>`).join('')}</div><p class="art-caption">情境插画 · 非实景照片</p><div class="corridor-cost"><h3>走完整条线，需要接受什么？</h3><p>${esc(r.cost)}</p><small>先探索愿望，再按天数、换住意愿与高原选择判断。这里不是已核实班次和价格的旅行产品。</small></div>`;}
export function entryRouteComparison(profile,result,route){const entry=result.routes.find(r=>r.id===profile.entryRouteId);if(!entry||entry.id===route?.id)return '';const names=entry.ids.map(id=>regionById[id].name).join(' → ');return `<section class="entry-comparison"><span class="small-label">回到最初让你心动的那条线</span><h2>${esc(names)}</h2><p>${entry.blocked.length?'现在不直接推荐走全线：'+entry.blocked.map(esc).join('；'):'这条线也能排进当前假期，但会有 '+entry.moves+' 次换住。可以与上面的建议对照，看看多一站是否值得。'}</p><div>${entry.blocked.length?'<button class="secondary" data-action="settings">调整天数与换住条件</button>':`<button class="secondary" data-action="route" data-id="${entry.id}">对照这条经典线的每天安排</button>`}<span>最初的心动已保留，不等于已经决定全去。</span></div></section>`;}
