import {corridors,corridorById,getCorridorsForBases} from './corridors.js?v=20260927-4';
import {regionById,scenes} from './journey.js?v=20260927-4';
import {sceneImage} from './media.js?v=20260927-4';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label={daytrip:'住原处，专程往返',replacement:'替换一个完整日',overnight:'需要另选住宿基地'};
const art={dalibaizu:'dali',northwest:'shangrila',central:'fuxian',honghe:'jianshui',west:'tengchong',south:'xishuangbanna'};
export const placeById=Object.fromEntries(corridors.flatMap(c=>c.places.map(p=>[p.id,{...p,corridorId:c.id}])));
export function corridorMap(c,selected=[]){
 const points=[...new Map([...c.stayBases,...c.places].map(p=>[p.id,p])).values()];
 const xs=points.map(p=>p.coordinates[0]),ys=points.map(p=>p.coordinates[1]),xmin=Math.min(...xs),ymin=Math.min(...ys),dx=Math.max(...xs)-xmin||1,dy=Math.max(...ys)-ymin||1;
 const bases=new Set(c.stayBases.map(b=>b.id));
 const positioned=points.map((p,i)=>({...p,n:i+1,px:55+(p.coordinates[0]-xmin)/dx*370,py:55+(1-(p.coordinates[1]-ymin)/dy)*190}));
 const placed=[];
 for(const p of positioned){p.x=p.px;p.y=p.py;let step=0;while(placed.some(q=>Math.hypot(p.x-q.x,p.y-q.y)<34)&&step<40){step++;const a=step*2.4,rad=12+step*1.8;p.x=Math.max(25,Math.min(450,p.px+Math.cos(a)*rad));p.y=Math.max(25,Math.min(265,p.py+Math.sin(a)*rad));}placed.push(p);}
 return `<figure class="corridor-map"><svg viewBox="0 0 480 290" role="img" aria-label="${esc(c.name)}地点相对方位示意"><defs><pattern id="grid-${c.id}" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M40 0H0V40" fill="none" stroke="#dfecec" stroke-width=".7"/></pattern></defs><rect width="480" height="290" rx="18" fill="#eff7f7"/><rect width="480" height="290" fill="url(#grid-${c.id})"/>${positioned.map(p=>`<g><title>${esc(p.name)}</title><path d="M${p.px} ${p.py}L${p.x} ${p.y}" stroke="#7797a5" stroke-width="1"/><circle cx="${p.x}" cy="${p.y}" r="14" fill="${selected.includes(p.id)?'#b96550':bases.has(p.id)?'#235b78':'#62959f'}" stroke="white" stroke-width="2"/><text x="${p.x}" y="${p.y+5}" font-size="15" font-family="sans-serif" text-anchor="middle" fill="white">${p.n}</text></g>`).join('')}<path d="M445 42V18m-4 6 4-6 4 6" stroke="#315d71" fill="none"/><text x="433" y="56" font-size="12" fill="#315d71">北</text></svg><div class="map-legend">${positioned.map(p=>`<span class="${bases.has(p.id)?'is-base':''}"><b>${p.n}</b>${esc(p.name)}</span>`).join('')}</div><figcaption>深色为可住宿地点；浅色为附近体验。编号为阅读方便略作错位，非导航路线。</figcaption></figure>`;
}
export function corridorExplorer(){return `<section class="corridor-explorer" id="regional-routes"><div class="section-line"><div><span class="small-label">不用把云南装进同一趟</span><h2>先选一片云南，再把日子过丰富。</h2><p>六个区域方向。点开看看，哪些地方可以一起住、哪些需要认真留时间。</p></div></div><div class="corridor-grid">${corridors.map((c,i)=>`<button class="corridor-card" data-action="corridor" data-id="${c.id}">${sceneImage(art[c.id],{alt:c.region+'区域情境插画，非当地实景照片',sizes:'(max-width:650px) 90vw, (max-width:1050px) 45vw, 410px'})}<span class="corridor-card-copy"><span class="corridor-area">${esc(c.region)}</span><strong>${esc(c.name)}</strong><span>${esc(c.tagline)}</span><span class="corridor-stops">${c.stayBases.map(b=>esc(b.name.split('／')[0])).join(' · ')}</span><span class="corridor-open">看看这一带怎样玩 <b aria-hidden="true">↗</b></span></span></button>`).join('')}</div></section>`;}
export function corridorDialogBody(id){const c=corridorById[id];if(!c)return '';return `<p class="region-story">${esc(c.tagline)}</p><div class="corridor-overview">${corridorMap(c)}<div><h3>住下来，才有不同的一天</h3><p>${esc(c.stayStrategy)}</p><div class="base-pills">${c.stayBases.filter(b=>regionById[b.id]).map(b=>`<button class="secondary" data-action="corridor-start" data-id="${b.id}" data-corridor="${id}">从${esc(regionById[b.id].name)}的心动开始</button>`).join('')}</div><small>先选一个画面探寻，不代表一定要把整条线走完。</small></div></div><h3 class="guide-days-title">沿着这一带，还有这些具体的日子</h3><div class="nearby-grid">${c.places.map(p=>placeCard(p)).join('')}</div><div class="corridor-cost"><h3>多一种体验，也要留出代价</h3><p>${esc(c.transportCost)}</p><p>${esc(c.chooseOneNote)}</p><small>${esc(c.season)}</small></div>`;}
function placeCard(p,baseIds=[],selections={}){const chosen=selections[p.anchorBase]===p.id;return `<article class="nearby-card ${chosen?'is-chosen':''}"><span class="nearby-type">${label[p.kind]}</span><h3>${esc(p.name)}</h3><p>${esc(p.tagline)}</p><div class="nearby-mini"><span>上午</span><p>${esc(p.oneDay.morning)}</p></div><button class="text-link" data-action="place" data-id="${p.id}">${chosen?'已经选入，查看安排':'展开这一天和代价'}</button></article>`;}
export function nearbySection(ids,profile){const matches=getCorridorsForBases(ids);return `<section class="nearby-section" id="nearby-options"><div class="section-line"><div><span class="small-label">住处可以少，体验可以多</span><h2>这条线路，还能怎样玩得更像你？</h2><p>选择附近的一天来替换原安排；需要换住的地方会重新算时间。</p></div></div>${matches.map(c=>`<div class="nearby-corridor"><div class="nearby-heading"><h3>${esc(c.name)}</h3><button class="text-link" data-action="corridor" data-id="${c.id}">看区域全貌</button></div><p class="nearby-strategy">${esc(c.chooseOneNote)}</p><div class="nearby-grid">${c.places.filter(p=>ids.includes(p.anchorBase)||p.kind==='overnight').map(p=>placeCard(p,ids,profile.excursions||{})).join('')}</div></div>`).join('')}</section>`;}
export function placeDialogBody(id,{route,result,profile}={}){const p=placeById[id];if(!p)return '';const c=corridorById[p.corridorId],base=regionById[p.anchorBase];const chosen=profile?.excursions?.[p.anchorBase]===id;const canReplace=route?.ids.includes(p.anchorBase)&&p.kind!=='overnight';return `<span class="tag">${esc(c.region)} · ${label[p.kind]}</span><p class="region-story">${esc(p.tagline)}</p><p>${esc(p.experience)}</p><div class="place-schedule">${[['上午',p.oneDay.morning],['下午',p.oneDay.afternoon],['晚上',p.oneDay.evening]].map(([t,s])=>`<div><span>${t}</span><p>${esc(s)}</p></div>`).join('')}</div><div class="day-extras"><p><strong>当地味道</strong>${esc(p.oneDay.food)}</p><p><strong>天气变了</strong>${esc(p.oneDay.backup)}</p></div><div class="corridor-cost"><h3>先看这份代价</h3><p>${esc(p.tradeoff)}</p><small>${p.kind==='overnight'?`需要重排住宿和转场，建议至少为这段预留 ${p.dayBudget} 个日程日；这不是实时交通报价。`:`它会替换${esc(base?.name||p.anchorBase)}的一个完整活动日，不增加假期天数。`}</small></div><div class="button-row">${canReplace?`<button class="primary" data-action="excursion" data-id="${id}">${chosen?'移除这天，恢复原安排':'用这一天替换原安排'}</button>`:p.kind==='overnight'?`<button class="primary" data-action="branch-route" data-id="${id}">看看留宿这里，几天才合适</button>`:`<button class="primary" data-action="corridor-start" data-id="${p.anchorBase}" data-corridor="${p.corridorId}">先探索${esc(base?.name||'这个基地')}</button>`}<button class="secondary" data-action="close">先保留现在的节奏</button></div>`;}
